Channels in four-channel images should be inverted.
mozilla/pdf.js pull request #10029
Opened 2018-09-01 14:34 UTC by photopea

This solves these images: https://github.com/mozilla/pdf.js/issues/9513 and does not break any other 4-channel JPGs that I have. But it could be good to test it with corresponding PDFs too, if you have any.

2018-09-01 14:47 UTC, timvandermeij requested changes
Thank you for looking into this. Aside from the comment below, please also add a reference test to this PR so we can avoid regressions later on. If you have a file that is free for us to use, please use the steps at https://github.com/mozilla/pdf.js/wiki/Contributing under `Generating reference images` to add it using the `test/add_test.js` tool.

2018-09-01 14:47 UTC, timvandermeij commented on src/core/jpg.js
> +        Y  = 255-data[i];
Here, and in other parts of the part, please leave one and only one space around the `-` and `=` operators, e.g., `Y = 255 - data[i]`.

2018-09-01 14:48 UTC, Snuffleupagus commented
> But it could be good to test it with corresponding PDFs too, if you have any.

Please see https://github.com/mozilla/pdf.js/wiki/Contributing#4-run-lint-and-testing for information about running test (and generating reference the images to test against). When modifying code residing in the `/src` folder, it's usually recommend/necessary to test locally when making changes.

Even without running any tests, I can pretty much guarantee that this patch would cause significant rendering regressions in existing test-cases.
*Ninja edit:* One broken example is https://github.com/mozilla/pdf.js/blob/master/test/pdfs/cmykjpeg.pdf

2018-09-01 21:35 UTC, photopea commented
@Snuffleupagus I extracted the "raw" JPG out of https://github.com/mozilla/pdf.js/blob/master/test/pdfs/cmykjpeg.pdf  and got this: 
![pic](https://user-images.githubusercontent.com/15955558/44947134-c69dc580-ae08-11e8-82e1-edc1269744d7.jpg)

And it is displayed as "black" by JPG viewers. Could it be, that there are extra parameters in a PDF file, that make it look "bright"?

2018-09-02 11:28 UTC, timvandermeij commented
It may indeed be more difficult than this PR if I'm reading the thread in https://github.com/haraldk/TwelveMonkeys/issues/141#issuecomment-108570213 and https://github.com/haraldk/TwelveMonkeys/issues/141#issuecomment-109429682 correctly.

2018-09-02 11:48 UTC, photopea commented
@timvandermeij So I suggest, that we give one more Boolean parameter to getData: JpegImage.getData(w,h,forceRGBoutput, invertChannels) - false by default. getData() will distribute this parameter to sub-functions.

Then, you will call  getData with the last parameter depending on information outside the JPEG stream. Can you find that information and rewrite all getData() calls? Then, I will update the JPEG decoder.

2018-09-02 12:29 UTC, timvandermeij commented
I don't know enough about JPEG decoding to know where to fetch this information from outside the JPEG stream, so I can't really help with this. I would suggest to look up the JPEG stream part in the PDF specification to find out how this should work before adding any parameters.

2018-09-02 13:17 UTC, closed without merging