automatically update URL hash, fixes #5753
mozilla/pdf.js pull request #10383
Opened 2018-12-26 20:51 UTC by tycho01

2018-12-27 23:06 UTC, timvandermeij commented
Does this address the concerns from https://github.com/mozilla/pdf.js/issues/5753#issuecomment-75451859?

2018-12-27 23:10 UTC, timvandermeij requested changes

2018-12-27 23:10 UTC, timvandermeij commented on web/app.js
> +    // update url on scroll
You can remove this comment and add it to the `setupHashUpdating` function below so it's clear what the objective of that function is.

2018-12-27 23:10 UTC, timvandermeij commented on web/app.js
> +    setupHashUpdating();
It feels like this is part of the initialization, so I think it should be moved above `this.initialized = true` above.

2018-12-27 23:10 UTC, timvandermeij commented on web/app.js
> +  let tid = false;
Unclear name; what does this represent?

2018-12-27 23:10 UTC, timvandermeij commented on web/app.js
> +    return PDFViewerApplication.pdfHistory.pushCurrentPosition();
I don't think `pushCurrentPosition` returns anything, so I think you can simplify by removing `updatePos` altogether and just calling this method in `setTimeout` below.

2018-12-27 23:10 UTC, timvandermeij commented on web/app.js
> +  let test = (evt) => {
`test` is a bit unclear; maybe `updateHash` is better?

2018-12-28 11:39 UTC, Snuffleupagus commented
Sorry, but this patch really isn't acceptable at all as far as I can tell, since it will be fighting with the (painstakingly implemented) history implementation already present in the default viewer.

First of all, the `PDFHistory` implementation is already *lazily* updating the history (using `updateviewarea` events), which renders this entire patch unnecessary. The only thing that this patch will do is to flood the browser history with lots of useless entries, which really isn't good and which the `PDFHistory` re-implementation sought to avoid.
Second of all, the `PDFHistory` method used here doesn't even touch the document URL so that's also strange (to say the least). However, that isn't at all something that should be "fixed", since hash changes doesn't really fit in great with the general history implementation (simply because the concept of *destinations* in the PDF format isn't a great fit for the web in general).

Quite frankly, this won't work and I don't understand why it's necessary to try and fix the referenced issue. Considering that even a working solution, whatever that would look like, will only add unnecessary complexity when all that's really needed is to press the `viewBookmark` button to obtain the current hash.

@timvandermeij This really ought to be closed as WONTFIX, as far as I'm concerned, and honestly that applies to the issue as well.

2019-01-06 18:21 UTC, closed without merging