Enable import/extensions of ESlint plugin to enforce all `import` have a `.js` file extension.
mozilla/pdf.js pull request #11519
Opened 2020-01-17 21:45 UTC by tamuratak

This PR enables the rule `import/extensions` of ESlint `import` plugin to enforce all `import` have a `.js` file extension. Related to  #11465. It would help your development.

- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md

2020-01-17 21:49 UTC, Snuffleupagus commented on .eslintrc
> +    "import/extensions": ["error", "always", {ignorePackages: true}],
Please make sure to sort the entries alphabetically in each section, hence this needs to be moved up.

Furthermore, please make sure to format this object consistently with the rest of the file; see for example https://github.com/mozilla/pdf.js/blob/40f531ee873f523e2991fd6c2ca00a336fdbfbdd/.eslintrc#L46

2020-01-17 21:51 UTC, Snuffleupagus requested changes
Finally, please make sure to include all of the information from the PR description in the *commit message* as well (such that it's available on the Git command line).

(Please note https://github.com/mozilla/pdf.js/wiki/Squashing-Commits when updating the patch.)

2020-01-17 22:14 UTC, tamuratak commented
Thank you for your review. I have edited as requested.

2020-01-19 16:25 UTC, timvandermeij commented
/botio-linux preview

2020-01-19 16:37 UTC, timvandermeij approved these changes

2020-01-19 16:37 UTC, merged

2020-01-19 16:37 UTC, timvandermeij commented
Thank you for improving this!