Remove the `RefSet` primitive
mozilla/pdf.js pull request #11977
Opened 2020-06-07 15:25 UTC by timvandermeij

It's only used in `src/core/obj.js` in a handful of places where nowadays a regular JavaScript set works too (the `RefSet` primitive predates the usage of ES6). Not only are built-in data structures often more efficient/optimized, it also avoids having to maintain a custom data structure.

Previously, each call to a `RefSet` method would cause `toString` to be called on the given `Ref`. As an additional bonus, using a regular JavaScript set allows us to limit the number of times `toString` is called now, simply by calling it once for `has` and `add` calls, for example. Therefore, this is also more efficient since it avoids the creation of intermediate strings.

2020-06-07 15:28 UTC, timvandermeij commented
/botio test

2020-06-07 16:20 UTC, Snuffleupagus requested changes
Really sorry, but I'm not at all keen on these changes!

The `RefSet` abstraction is, as its name suggests, written specifically to operate only on `Ref` objects and I worry that simply using Sets directly in this manner makes the code more difficult to read/modify and that bugs are thus much easier to introduce.
Essentially, in the worker, it's generally preferable to avoid depending directly on the stringified version of a `Ref` object if possible.

Basically, unless there's test-cases where benchmarking shows *clear* improvements, then I'd ask that we please don't make these changes.

2020-06-07 17:05 UTC, timvandermeij commented
I understand your concern here. I have updated the patch to keep `RefSet`, but instead refactor it to use a set internally instead of an object. Would that be better?

2020-06-07 17:05 UTC, timvandermeij commented
/botio unittest

2020-06-07 18:47 UTC, Snuffleupagus commented
> I have updated the patch to keep `RefSet`, but instead refactor it to use a set internally instead of an object. Would that be better?

Yes, that seems completely fine by me; thank you for doing this!

(Also, possibly this could make `RefSet.has()` more efficient since I recall some older issues where avoiding `in` usage helped performance.)

---

Just for good measure, let's run all tests :-)

/botio test

2020-06-07 21:15 UTC, merged

2020-07-04 18:07 UTC, Snuffleupagus commented
An idea could be to try and do something similar, but obviously with a `Map` instead, for the `RefSetCache`; I'd happily review such a patch :-)