Fix getVisibleElements helper in RTL-locales
mozilla/pdf.js pull request #12464
Opened 2020-10-09 14:24 UTC by baloone

This PR fixes the issue 12453. I'm not sure about the name of the auxiliary function `isElementNextAfterViewHorizontally`.

2020-10-09 19:50 UTC, timvandermeij commented
/botio-linux preview

2020-10-11 12:54 UTC, timvandermeij commented
@Snuffleupagus If you have time, could you take a look at this PR? It looks reasonable to me, but my experience with the (not so trivial) `getVisibleElements` function is limited.

2020-10-11 13:01 UTC, timvandermeij reviewed
I just noticed that we have unit tests for the `getVisibleElements` function in `test/unit/ui_utils_spec.js`. I don't know how difficult this it to test, but it would be great if you could extend the unit tests for this PR so that we prevent this from regressing again in the future.

2020-10-12 10:00 UTC, Snuffleupagus requested changes
As mentioned in https://github.com/mozilla/pdf.js/pull/12464#pullrequestreview-506177403, we need at least a *basic* unit-test for this (called e.g. `handles horizontal scrolling with RTL-documents correctly`).
I'd suggest defining a suitable `scrollEl`, similar but probably not identical to https://github.com/mozilla/pdf.js/blob/49791f55b3cb4ae1cef68a6573e764aa0db3b5fb/test/unit/ui_utils_spec.js#L740-L746 with pages defined e.g. as in https://github.com/mozilla/pdf.js/blob/49791f55b3cb4ae1cef68a6573e764aa0db3b5fb/test/unit/ui_utils_spec.js#L730-L736 and with the test doing something like
```javascript
const visibleSorted = getVisibleElements(
  scrollEl,
  views,
  /* sortByVisibility = */ true,
  /* horizontal = */ true,
  /* rtl = */ true
);
```
and then checking that `visibleSorted` has the expected order (see how that's implemented in the existing test).

2020-10-20 21:35 UTC, baloone commented
I added the two suggested changes and a test

2020-10-24 14:14 UTC, timvandermeij commented
/botio-linux preview

2020-10-24 14:22 UTC, timvandermeij commented
/botio-linux unittest

2020-10-24 15:03 UTC, timvandermeij approved these changes

2020-10-24 15:03 UTC, merged

2020-10-24 15:04 UTC, timvandermeij commented
Thank you for fixing this!