JS -- Add support for buttons
mozilla/pdf.js pull request #12637
Opened 2020-11-18 17:56 UTC by calixteman

* radio buttons
 * checkboxes

2020-12-08 01:17 UTC, brendandahl commented
Needs a rebase. Did a quick test with it rebased and radio buttons are working as expected, but radio checkboxes are not. http://www.windjack.com/DownLoads/RadioCheckBox_AcroForm.pdf

Would be good if we could get the puppeteer testing added, so then we can add tests for this first.

2020-12-08 14:42 UTC, calixteman commented
The radio checkboxes have no JS here so there is a bug in annotation.js itself (anyway there is a bug in my code to manage such a situation).

2020-12-14 17:40 UTC, brendandahl commented
Can we add a test for this code now too?

2020-12-18 20:55 UTC, calixteman commented
/botio test

2020-12-21 17:36 UTC, brendandahl requested changes

2020-12-21 17:36 UTC, brendandahl commented on test/integration/scripting_spec.js
> +            await page.waitForTimeout(100);
As we've seen in other tests, using timeouts is a big cause of intermittent failures. Can we add an annotationchanged event or something instead?

2020-12-21 17:36 UTC, brendandahl commented on test/integration/scripting_spec.js
> +          await page.waitForTimeout(100);
Same here, why is this timeout needed is there an event that can be used instead?

2020-12-22 18:13 UTC, brendandahl commented
/botio test

2020-12-23 05:49 UTC, brendandahl commented
/botio-windows test

2020-12-23 06:18 UTC, merged

2020-12-23 06:18 UTC, brendandahl commented
/botio makeref