Update README.md
mozilla/pdf.js pull request #12663
Opened 2020-11-26 05:07 UTC by Deepak-du

update some new features

2020-11-26 10:08 UTC, Deepak-du commented
@timvandermeij please review this

2020-11-26 10:11 UTC, Snuffleupagus requested changes
Please remember to write a good *commit message*, explaining what you're changing and why, since "Update README.md" isn't terribly descriptive.

Also, please see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

2020-11-26 10:11 UTC, Snuffleupagus commented on README.md
> +# [PDF.js](https://mozilla.github.io/pdf.js/) &middot; [![Build Status](https://travis-ci.org/mozilla/pdf.js.svg?branch=master)](https://travis-ci.org/mozilla/pdf.js) [![License](https://img.shields.
It's not really clear that we need to list all of these things at the top of the README, note how e.g. the license information is already listed at the *top* of https://github.com/mozilla/pdf.js

Furthermore, given how infrequent the PDF.js Twitter-account is updated (the last post was 4.5 years ago), it probably doesn't make sense to list that at the top of the README either!?

Hence I'd suggest simplifying this to only:
```suggestion
# [PDF.js](https://mozilla.github.io/pdf.js/) [![Build Status](https://travis-ci.org/mozilla/pdf.js.svg?branch=master)](https://travis-ci.org/mozilla/pdf.js) [![npm version](https://img.shields.io/npm/v/pdfjs-dist)](https://www.npmjs.com/package/pdfjs-dist)
```

2020-11-26 10:11 UTC, Snuffleupagus commented on README.md
> -
Please don't remove blank lines, since they aid with readability of the "raw"-file.

2020-11-27 10:02 UTC, Snuffleupagus commented
So far it seems that only *some* of the review comments have been addressed here, hence please fix *all* of them and remember both of the points mentioned in https://github.com/mozilla/pdf.js/pull/12663#pullrequestreview-539149098 as well since in its current form this unfortunately cannot land.

2020-12-02 13:23 UTC, closed without merging