fix(a11y): resolve sidebar, find, toolbar missing aria-expanded and aria-controls state
mozilla/pdf.js pull request #12941
Opened 2021-02-01 22:32 UTC by justinribeiro

In testing, screen readers such as JAWS have trouble understanding the expanded state of the buttons that expand hidden menus due to lacking `aria-expanded` attribute. Also, given that the buttons do not contain the controlled/shown element, they should also define the `aria-controls` attribute with associated element id per https://www.w3.org/TR/wai-aria-1.1/#aria-expanded

This fixes adds these requirements for the sidebar, find, and secondary toolbar buttons.

2021-02-03 19:54 UTC, timvandermeij commented
/botio-linux preview

2021-02-03 20:02 UTC, Snuffleupagus requested changes
Please keep in mind that the *commit message* itself should contain all of the information found in https://github.com/mozilla/pdf.js/pull/12941#issue-565523643, such that it's also available e.g. on the Git command line.

2021-02-03 20:04 UTC, timvandermeij commented
Looks good to me with an amended commit message.

2021-02-06 00:10 UTC, justinribeiro commented
@Snuffleupagus per @timvandermeij commit message amended. Cheers!

2021-02-06 18:16 UTC, timvandermeij approved these changes

2021-02-06 18:16 UTC, merged

2021-02-06 18:16 UTC, timvandermeij commented
Thank you for improving this!