XFA - Fix lot of layout issues
mozilla/pdf.js pull request #13402
Opened 2021-05-19 10:07 UTC by calixteman

- I thought it was possible to rely on browser layout engine to handle layout stuff but it isn't possible
    - mainly because when a contentArea overflows, we must continue to layout in the next contentArea
    - when no more contentArea is available then we must go to the next page...
    - we must handle breakBefore and breakAfter which allows to "break" the layout to go to the next container
  - Sometimes some containers don't provide their dimensions so we must compute them in order to know where to put
    them in their parents but to compute those dimensions we need to layout the container itself...
  - See top of file layout.js for more explanations about layout.
  - fix few bugs in other places I met during my work on layout.

2021-05-19 10:17 UTC, Snuffleupagus commented on src/core/xfa/layout.js
> +/*
Nit: Please remember to use the following comment formatting, for overall consistency in the code-base.
```javascript 
/**
 * How layout works?
 *
 * ...
 */
```

2021-05-24 22:37 UTC, brendandahl requested changes

2021-05-24 22:37 UTC, brendandahl commented on src/core/xfa/template.js
> +      for (; this[$extra].attempt < 3; this[$extra].attempt++) {
Make number of attempts a constant.

2021-05-25 15:41 UTC, brendandahl approved these changes
r+ needs the comment in layout.js updated though.

2021-05-25 15:54 UTC, calixteman commented
/botio unittest

2021-05-25 16:01 UTC, calixteman commented
/botio-linux unittest

2021-05-25 16:25 UTC, calixteman commented
/botio-linux unittest

2021-05-25 16:27 UTC, calixteman commented
/botio-linux unittest

2021-05-25 16:31 UTC, merged