Annotation & XFA: Scale the font size in choicelist using zoom factor (bug 1715996)
mozilla/pdf.js pull request #13868
Opened 2021-08-04 12:46 UTC by calixteman

- this is an accessibility issue which could be painful for some people with visual disabilities.

2021-08-04 13:15 UTC, Snuffleupagus requested changes

2021-08-04 13:15 UTC, Snuffleupagus commented on web/viewer.css
> +  --zoom-factor: 1;
This needs to be placed in `pdf_viewer.css` instead, since otherwise you're breaking the standalone viewer components.

2021-08-04 13:18 UTC, calixteman commented on src/core/xfa/template.js
> +    const fontSize = (field.font && field.font.size) || 10;
In XFA, the default font-size is 10 (see specs for v3.3) so it's why.

2021-08-04 13:49 UTC, Snuffleupagus commented
/botio test

2021-08-04 14:27 UTC, Snuffleupagus commented
There seem to be one regression in `chrome-annotation-choice-widget-forms-page1`.

2021-08-04 14:37 UTC, calixteman commented
Yep, I forgot to set the font size only for combo choicelist.

2021-08-04 14:38 UTC, calixteman commented
/botio test

2021-08-04 15:14 UTC, Snuffleupagus commented
> Yep, I forgot to set the font size only for combo choicelist.

It looks like you forgot to push the changes?

Also, a couple of the `integrationtest`s fail on all platforms/browser, so those tests may need some updates as well?

2021-08-04 15:35 UTC, calixteman commented
/botio test

2021-08-04 16:12 UTC, calixteman commented
/botio-linux test

2021-08-04 16:47 UTC, calixteman commented
/botio-linux preview

2021-08-04 18:01 UTC, Snuffleupagus commented
Testing the preview, with the `annotation-choice-widget.pdf` file from the test-suite, there's now a large of amount of "padding" in the dropdowns (i.e. *similar* to the previously failing ref-tests above); please see the following screen-shot:

![image](https://user-images.githubusercontent.com/2692120/128231055-d023ea7e-29a2-455e-998c-874869190edb.png)

2021-08-04 18:38 UTC, calixteman commented
/botio test

2021-08-04 18:42 UTC, calixteman commented
> Testing the preview, with the `annotation-choice-widget.pdf` file from the test-suite, there's now a large of amount of "padding" in the dropdowns (i.e. _similar_ to the previously failing ref-tests above); please see the following screen-shot:
> 

I thought adding font-size stuff on an `optgroup` will help to reduce the number of setProperty but I misunderstood what `optgroup` is and it's why some extra blanks were added at the beginning of the line.
So finally, I added font-size stuff on each `option`, if you've a good idea to avoid that, please propose.

2021-08-04 20:10 UTC, calixteman commented
The differences are due to the fact we use the fontsize from the pdf.

2021-08-04 20:11 UTC, calixteman commented
/botio-linux preview

2021-08-05 08:30 UTC, Snuffleupagus commented
> So finally, I added font-size stuff on each `option`, if you've a good idea to avoid that, please propose.

Given that documents likely won't contain more than perhaps a handful of these form elements per page, and that we unload pages that aren't visible, I'm not sure if this really is a big problem (unfortunately I don't have a better idea here).

2021-08-05 08:44 UTC, Snuffleupagus commented
> So finally, I added font-size stuff on each `option`, if you've a good idea to avoid that, please propose.

Given that documents likely won't contain more than perhaps a handful of these form elements per page, and that we unload pages that aren't visible, I'm not sure if this really is a going to be a big problem.
Unfortunately I've not got a better idea off the top of my head, so let's do this for now (and I'll try to fix the standalone `PDFPageView` case in a follow-up).

2021-08-05 08:45 UTC, merged

2021-08-05 08:45 UTC, Snuffleupagus commented
/botio makeref