Use a faster method to determine whether the number is even or odd
mozilla/pdf.js pull request #14272
Opened 2021-11-14 06:18 UTC by Atul-Kumar-Official

Bit masking was slower than directly checking whether the number is odd or even. You can check the speed/time complexity of the algorithm by profiling and timestamping both chunks of code.

2021-11-14 09:03 UTC, Snuffleupagus requested changes
> Bit masking was slower than directly checking whether the number is odd or even.

The "directly checking"-part reads a little strangely, since your patch is actually using the [remainder operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder) which is (more or less) essentially the modulo operator.

> You can check the speed/time complexity of the algorithm by profiling and timestamping both chunks of code.

If you're claiming that changes you're making result in faster code, please actually include said measurements in the commit message (and PR description). Also, please keep in mind that micro-benchmarks are usually of quite limited usefulness.

Hence, in order for us to consider this patch, please find a suitable PDF document and then follow https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes#using-the-test-runner to provide performance results in the context of an entire PDF document (in this case, you want to use a `text`-test when benchmarking).

---

Finally, please make sure that the commit message actually contains information about what code the patch is modifying (e.g. adding " in `src/core/bidi.js`" to the end of first line would've helped tremendously), since you otherwise have no idea what the patch does without actually reading the code.

2021-11-14 14:33 UTC, Atul-Kumar-Official commented
I measured the time taken by both the chunks of code and here is the result:
Bit Masking: 0.0346ms
Modulus Operator: 0.0184ms

I measured the time taken by both the chunks of code 100 times and the above mentioned time is the average time taken

2021-11-14 14:46 UTC, Snuffleupagus requested changes
> I measured the time taken by both the chunks of code and here is the result: Bit Masking: 0.0346ms Modulus Operator: 0.0184ms
> 
> I measured the time taken by both the chunks of code 100 times and the above mentioned time is the average time taken

Please note the as mentioned above, see https://github.com/mozilla/pdf.js/pull/14272#pullrequestreview-805447201, micro-benchmarks are usually not all that helpful (and you've not said anything about the *environment*/*browser* used for your test; here we're mostly concerned with performance in Firefox).
Keep in mind that micro-benchmarks can sometimes even be completely misleading, since they may trigger JavaScript engines to optimize away code in a manner that's not representative when the code is run as part of a larger program.

Hence, please following the benchmarking instructions provided in https://github.com/mozilla/pdf.js/pull/14272#pullrequestreview-805447201.

2021-11-17 09:30 UTC, MuhammadAmin86 commented
function user(){
const number = 0;
number = prompt("Enter a number: ");


const result = (number % 2  == 0);
 }

 console.log(`The number is ${result}.`);
[please kindly identify mistake and create a program i am a new learner please help me this code is in javascript]

2021-11-17 09:36 UTC, Atul-Kumar-Official commented
This is not a big mistake. You just need to put the console.log statement
in the function's scope so that whenever you call the function and a user
types the number in the prompt box, it gets printed in the console

On Wed, 17 Nov, 2021, 3:00 pm MuhammadAmin86, ***@***.***>
wrote:

> function user(){
> const number = 0;
> number = prompt("Enter a number: ");
>
> const result = (number % 2 == 0);
> }
>
> console.log(The number is ${result}.);
> [please kindly identify mistake and create a program i am a new learner
> please help me this code is in javascript]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/pdf.js/pull/14272#issuecomment-971396617>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU5VKLK2NZROSJMBSVLP2P3UMNY4BANCNFSM5H7PWHKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-17 09:53 UTC, Snuffleupagus commented
Closing as WONTFIX, since without proper benchmarking results we unfortunately can't really evaluate the patch.

2021-11-17 09:53 UTC, closed without merging