Remove the invisible format marks from the text chunks
mozilla/pdf.js pull request #14483
Opened 2022-01-23 22:04 UTC by calixteman

2022-01-23 22:21 UTC, Snuffleupagus requested changes

2022-01-23 22:21 UTC, Snuffleupagus commented on test/test_manifest.json
> +      "type": "load"
This should be `"type": "text"` instead, right?

2022-01-23 22:21 UTC, Snuffleupagus commented on test/unit/api_spec.js
> +    it("gets text content, with invisible text mark (issue 9186)", async function () {
Given that the test-case is linked, you'll need to add the following block to fix the GitHub Actions failure:
```javascript
if (isNodeJS) {
  pending("Linked test-cases are not supported in Node.js.");
}
```

2022-01-24 13:47 UTC, Snuffleupagus commented
/botio test

2022-01-24 14:35 UTC, Snuffleupagus commented
The unit-test failures are already tracked elsewhere, so let's just check the integration-tests again.

/botio integrationtest

2022-01-24 14:41 UTC, calixteman commented
What's the issue number for the scripting unit test failure (I can reproduce locally) ?

2022-01-24 14:56 UTC, Snuffleupagus commented
> What's the issue number for the scripting unit test failure (I can reproduce locally) ?

Please see issue #14488 (it's too bad that GitHub hasn't got a proper "needinfo" functionality, besides the general @-ing a user).

/botio integrationtest

2022-01-24 15:12 UTC, Snuffleupagus approved these changes
r=me, since this looks reasonable.

(The intermittent integration-test failures on Windows, while unfortunate, should really be completely unrelated to this patch.)

2022-01-24 16:27 UTC, calixteman commented
> r=me, since this looks reasonable.
> 
> (The intermittent integration-test failures on Windows, while unfortunate, should really be completely unrelated to this patch.)

Yeah I recently saw it too...

2022-01-24 16:52 UTC, merged

2022-01-24 16:52 UTC, calixteman commented
/botio makeref