Unblock the load event when the pdf has a password (bug 1801341)
mozilla/pdf.js pull request #15727
Opened 2022-11-22 16:49 UTC by calixteman

2022-11-22 17:49 UTC, Snuffleupagus requested changes
Note that the reason for delaying the "load" event was so that automatic printing of PDF documents in `iframe`-elements still works; please see https://bugzilla.mozilla.org/show_bug.cgi?id=1618553
With these changes we basically regress that specifically for password-protected PDF documents, is that actually what we want to do here?

2022-11-22 17:49 UTC, Snuffleupagus commented on web/app.js
> +      // callback then the viewer can never shows (bug 1801341).
Nit:
```suggestion
      // callback then the viewer never shows (bug 1801341).
```

2022-11-22 21:25 UTC, calixteman commented
> Note that the reason for delaying the "load" event was so that automatic printing of PDF documents in `iframe`-elements still works; please see https://bugzilla.mozilla.org/show_bug.cgi?id=1618553 With these changes we basically regress that specifically for password-protected PDF documents, is that actually what we want to do here?

I'm not super excited by the idea to break something...
Do you know if there is a way to know that an element with a specific id (here the dialog password) is visible within an iframe (I had a look at `IntersectionObserver` but I didn't to make it working within an iframe created with `createElement`) ?

2022-11-22 21:54 UTC, Snuffleupagus commented
> Do you know if there is a way to know that an element with a specific id (here the dialog password) is visible within an iframe (I had a look at `IntersectionObserver` but I didn't to make it working within an iframe created with `createElement`) ?

No idea unfortunately :-(

---

However, if we implement this with the tweak suggested in https://github.com/mozilla/pdf.js/pull/15727#discussion_r1029797641 we should be limiting any problems considerably.
Given that you can't really trigger auto-printing on a *password-protected* PDF document embedded in an `iframe` using its "load"-event, since that'd always require the user to manually input a password, we should be pretty safe (at least I *think* so).

2022-11-23 09:32 UTC, Snuffleupagus approved these changes
r=me, with the nit from https://github.com/mozilla/pdf.js/pull/15727#discussion_r1029651886 taken care of; thank you!

2022-11-23 10:19 UTC, calixteman commented
/botio integrationtest

2022-11-23 10:43 UTC, calixteman commented
/botio-windows integrationtest

2022-11-23 11:09 UTC, merged