Write some {Object} in api.js more precise
mozilla/pdf.js pull request #16159
Opened 2023-03-16 00:00 UTC by nmtigor

I didn't add new types. Only types in the following categories are concerned:
* browser-native types, e.g. `CanvasRenderingContext2D`
* ts-native types, e.g. `Record<string, string>`
* pdf.js-native types, e.g. `BaseCanvasFactory`

2023-03-16 07:43 UTC, Snuffleupagus requested changes, later dismissed
When updating the PR, please remember to write a slightly more detailed *commit message* (in addition to the PR description here at GitHub).

2023-03-16 07:43 UTC, Snuffleupagus commented on src/display/api.js
> + *   headers.
Please note that the primary use-case for the JSDoc-comments is to generate https://mozilla.github.io/pdf.js/api/draft/index.html, and consequently we can't have any TypeScript-specific types here; please just revert this change.

2023-03-16 07:43 UTC, Snuffleupagus commented on src/display/api.js
> + * @property {Record<string, TextStyle>} styles - {@link TextStyle} objects,
Please note that the primary use-case for the JSDoc-comments is to generate https://mozilla.github.io/pdf.js/api/draft/index.html, and consequently we can't have any TypeScript-specific types here; please just revert this change.

2023-03-16 07:43 UTC, Snuffleupagus commented on src/display/api.js
> + *   {new DOMCanvasFactory()}.
That parameter is first of all deprecated, which means that there's no reason to update it. Secondly, the user may provide a custom factory that's *not* actually `instanceof BaseCanvasFactory` which means that this change wasn't entirely accurate; please just revert this change.

2023-03-16 07:43 UTC, Snuffleupagus commented on src/display/api.js
> + *    to use for the canvas.
Too much indentation on the second line.
```suggestion
 * @property {CanvasGradient | CanvasPattern | string} [background] - Background
 *   to use for the canvas.
```

2023-03-25 14:42 UTC, timvandermeij commented
Looks reasonable to me like this. Could you squash the commits into one and we'll review again once that is done?

2023-04-01 13:24 UTC, timvandermeij approved these changes

2023-04-01 13:26 UTC, timvandermeij commented
LGTM to me. @Snuffleupagus Since you have a change request open here, could you check again?

2023-04-01 13:57 UTC, merged