[Editor] Fix the resizing of an editor when it's rotated (bug 1847268)
mozilla/pdf.js pull request #16793
Opened 2023-08-04 16:31 UTC by calixteman

There are 2 rotation we've to deal with: the viewer one and the editor one. The previous implementation was a bit complex and having to deal with these rotation would have potentially increase it.
So this patch aims to simplify the implementation and deal with all the possible cases.
The main idea is to transform the mouse deltas according to the rotations and then apply the resizing in the page coordinates system.

2023-08-05 07:17 UTC, Snuffleupagus requested changes
It seems that the style changes rely heavily on CSS nesting, a feature that's new enough that I cannot find a dedicated MDN page for it. Looking at https://caniuse.com/css-nesting confirms that browser support isn't great yet, since e.g. even Firefox ESR cannot use this.

That said, we might still be able to use this iff it can be polyfilled automatically. There seems to be a PostCSS package available, however I've not tested if it works, hence please:
 - Add the https://www.npmjs.com/package/postcss-nesting package, see also https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting#readme
 - Import it in the `gulpfile` similar to how other PostCSS plugins are handled.
 - Search for `postcssDirPseudoClass()` and modify *all the relevant* call-sites to include the new plugin; e.g. https://github.com/mozilla/pdf.js/blob/399475247feeffb3184d1c865530930a8638aa0e/gulpfile.mjs#L970-L972 would become
   ```js
     .pipe(
        postcss([
          postcssDirPseudoClass(),
          postcssNesting(),
          autoprefixer(AUTOPREFIXER_CONFIG)
        ])
      )
    ```
 - Build the GENERIC viewer and check that the relevant CSS rules are rewritten as expected.

2023-08-07 06:47 UTC, Snuffleupagus commented on test/integration/stamp_editor_spec.js
> +            return;
Here, and elsewhere below, why is `pending` being replaced with early return?

2023-08-07 06:47 UTC, Snuffleupagus commented on src/display/editor/editor.js
>        this.parent.div.classList.remove(resizingClassName);
Looking at the updated CSS, do we still use the `resizingClassName` for anything?

If not this line, together with https://github.com/mozilla/pdf.js/blob/915352ec2228be5d836b7a405c633112a0bbe57a/src/display/editor/editor.js#L454-L457, can probably be removed now.

2023-08-07 06:49 UTC, Snuffleupagus commented on web/annotation_editor_layer_builder.css
>  }
This should be significantly improved, enough to call it fixed I think, when this patch is rebased on PR #16799.

2023-08-08 10:54 UTC, calixteman commented
I just updated the integration test about the cursor name.

2023-08-08 14:44 UTC, Snuffleupagus approved these changes
Seems to work as advertised :-)

r=me, thank you!

2023-08-08 16:01 UTC, calixteman commented
/botio integrationtest

2023-08-08 16:24 UTC, merged