Use page.evaluateHandle when we want to await on document promises in integration tests
mozilla/pdf.js pull request #17387
Opened 2023-12-06 14:30 UTC by calixteman

For reference: https://github.com/mozilla/pdf.js/pull/17378#issuecomment-1842864939

2023-12-06 14:30 UTC, calixteman commented
/botio integrationtest

2023-12-06 14:48 UTC, calixteman commented
/botio integrationtest

2023-12-07 09:25 UTC, OrKoN commented on test/integration/test_utils.mjs
> +  const handle = await page.evaluateHandle(sel => {
That's right, assuming that scrollIntoView is awaited at the call sites. But the current version also work!

2023-12-07 09:41 UTC, OrKoN approved these changes

2023-12-07 09:45 UTC, calixteman commented on test/integration/test_utils.mjs
> +  const handle = await page.evaluateHandle(sel => {
It's probably better to have one pattern: it avoids to wonder which one we should choose and avoids to make the bad choice.
That said, @OrKoN thank you for the `evaluatorHandle` trick.

2023-12-07 11:21 UTC, Snuffleupagus requested changes
There's a few cases of `fdescribe` left in the patch, which thus disables most tests. Please revert those and run all integration-tests, and I'll do a final review later today (assuming passing tests).

2023-12-07 13:21 UTC, calixteman commented on test/integration/test_utils.mjs
> +    cb => [new Promise(eval(`(${cb})`))],
If you've a better idea, I take it. But for now, we can likely keep it without any concerns.

2023-12-07 15:45 UTC, Snuffleupagus approved these changes
r=me, with one more question; thank you!

2023-12-07 15:45 UTC, Snuffleupagus commented on test/integration/test_utils.mjs
> +  const hasTimedout = await handle.evaluate(([p]) => p);
Nit: For overall consistency, shouldn't this use the new helper function instead?
```suggestion
  const hasTimedout = await awaitPromise(handle);
```

2023-12-07 16:00 UTC, calixteman commented
/botio integrationtest

2023-12-07 16:21 UTC, merged