Workaround WebKit canvas rendering bug when zooming PDFs
mozilla/pdf.js pull request #17571
Opened 2024-01-24 10:29 UTC by nicolo-ribaudo

WebKit has a rendering bug when rendering canvas that have their width relative to their parent, and their parent is resized. This causes a "tearing" effect when zooming in PDFs past a certain threshold, which is devide-dependent but tends to be between 120% and 200%.

The DOM structure around the canvas is as follows:
```
div.pdfViewer [ --scale-factor: ...; ]
  > div.page [ width: round(var(--scale-factor) * ..., 1px); ]
    > div.canvasWrapper
      > canvas
```

Setting `width: inherit` on the div.canvasWrapper and on the canvas is equivalent to explicitly specifying the same `width` property in pixels as in div.page, thus making Safari properly redraw the canvas on resize.

See https://bugs.webkit.org/show_bug.cgi?id=267986 for more details on the WebKit bug.

Fixes #16155, fixes #16329, fixes #17459

https://github.com/mozilla/pdf.js/discussions/17459 shows a good video of what the rendering bug fixed by this PR is.

---

Note that it's very easy to fix this for downstream consumers of pdf.js. I think adding this CSS to their page is enough:
```css
.pdfViewer .canvasWrapper,
.pdfViewer .page canvas[zooming] {
  width: inherit !important;
}
```
however, I'm opening this PR because
1. I noticed that multiple people submitted issues about it
2. the fix is very minimal and does not impact other browser, given than in this case `width: 100%` and `width: inherit` _should_ have the same behavior.

Marking as a draft because I tested it on an iPad but I'm waiting for something with an iPhone to confirm that this indeed works for them too :)

2024-01-24 10:37 UTC, Snuffleupagus requested changes
Sorry, but *why* is this not a WebKit bug that ought to be addressed in those browsers rather than worked-around here?

> 2\. the fix is very minimal and does not impact other browser, given than in this case `width: 100%` and `width: inherit` _should_ have the same behavior.

Please note that we really want to avoid introducing any browser-specific compatibility hacks in the main code-base.
The reasons for this is to not negatively impact readability/maintainability of the code, and to avoid having to deal with any potential regressions later (given the "should"-part this just seems like unnecessary risk).

Please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target for the PDF.js library.

2024-01-24 16:35 UTC, aibolit commented on web/pdf_viewer.css
> +   * is devide-dependent but tends to be between 120% and 200%.
Spellcheck
```suggestion
   * is device-dependent but tends to be between 120% and 200%.
```

2024-01-25 10:30 UTC, box10 commented
thanks so much. this seems to work fine on iPad and from my quick test, also on iPhone

2024-04-10 09:43 UTC, Snuffleupagus commented
As mentioned in https://github.com/mozilla/pdf.js/pull/17571#pullrequestreview-1841057316 we *generally* don't want to add browser-specific compatibility hacks in the main code base, even more so when the browser in question is only listed as "Mostly" supported; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#legacy-build

2024-04-10 09:43 UTC, closed without merging

2024-04-10 15:16 UTC, calixteman commented
I had a look and removing the `display` property:
https://github.com/mozilla/pdf.js/blob/f3b03e5c4bbb786dc05204cc803558909a083053/web/pdf_viewer.css#L158
(or setting it to `inline`) fixes the issue for me with Safari on mac.
I don't see any reason why it's `block`, as far as I can tell it comes from:
https://github.com/mozilla/pdf.js/pull/136
Since we add some svg elements in the canvas wrapper when highlighting, I checked if everything is ok and it seems to be.
So I guess we can remove it.
And tbh, I wasn't super excited by the original patch, especially because it's hard to test and because I had the feeling that even if it was small it could have led to easily introduce some regressions in the future.
@nicolo-ribaudo, could you check that it fixes the issue on ipad/ios (I don't have such devices) ? and if it's ok for you, please make an other PR.

2024-04-10 16:49 UTC, Snuffleupagus commented
Re https://github.com/mozilla/pdf.js/pull/17571#issuecomment-2047832265, please let's make a new release first (as mentioned elsewhere) *before* we consider hacking around a Safari-only bug.

2024-04-10 16:51 UTC, calixteman commented
> Re [#17571 (comment)](https://github.com/mozilla/pdf.js/pull/17571#issuecomment-2047832265), please let's make a new release first (as mentioned elsewhere) _before_ we consider hacking around a Safari-only bug.

Yes of course, there is no rush here.