When updating, write the xref table in the same format as the previous one (bug 1878916)
mozilla/pdf.js pull request #17636
Opened 2024-02-08 09:56 UTC by calixteman

The specs are unclear about what kind of xref table format must be used.
In checking the validity of some pdfs in the preflight tool from Acrobat we can guess that having the same format is the correct way to do.
The pdf in the mentioned bug, after having been changed, wasn't correctly displayed in neither Chrome nor Acrobat: it's now fixed.

2024-02-09 13:27 UTC, Snuffleupagus requested changes
Leaving a couple of comments based on an initial (quick) look.
Please run all tests, and I'll try to finish reviewing this ASAP.

2024-02-09 13:27 UTC, Snuffleupagus commented on src/core/core_utils.js
> +  // n bits are required for numbers up 2^n - 1.
Is this line perhaps missing a word?
```suggestion
  // n bits are required for numbers up to 2^n - 1.
```

2024-02-09 13:27 UTC, Snuffleupagus commented on src/core/core_utils.js
> +  return Math.ceil(Math.ceil(Math.log2(1 + x)) / 8);
The expression in the comment doesn't *appear* to match the code fully, unless I'm missing something?
```suggestion
  // So for a number x, we need ceil(log2(1 + x)) bits.
  return Math.ceil(Math.ceil(Math.log2(1 + x)) / 8);
```

2024-02-09 13:27 UTC, Snuffleupagus commented on src/core/worker.js
> +          useXrefStream: xref.topDict?.get("Type")?.name === "XRef",
It's not immediately clear, when looking at this, what kind of data you're checking for here.
Please note that we have a helper function for this very case, [see here](https://github.com/mozilla/pdf.js/blob/7cfcd00a385314a05e0ff247d80262200a0e1556/src/core/primitives.js#L391-L395), which allows us to write this as follows.
```suggestion
          useXrefStream: isDict(xref.topDict, "XRef"),
```

2024-02-11 21:40 UTC, Snuffleupagus commented on src/core/writer.js
> +function getTrailerDict(xrefInfo, newRefs, isXrefStream) {
For overall consistency, can we keep the `useXrefStream` name throughout the code?
```suggestion
function getTrailerDict(xrefInfo, newRefs, useXrefStream) {
```

2024-02-11 21:40 UTC, Snuffleupagus commented on src/core/writer.js
> +    }
I'm finding this quite hard to wrap my head around, any chance that a good comment can be added to explain what's going on here?
(Or, if at all possible, perhaps the code can be simplified a little bit?)

2024-02-11 21:40 UTC, Snuffleupagus commented on src/core/writer.js
> +  }
Similarly in this function, a comment would help here.

2024-02-12 09:36 UTC, calixteman commented
/botio test

2024-02-12 13:12 UTC, jberkenbilt commented
Chiming in here, qpdf recognizes this as a valid file, and my manual decoding of the file also suggests that its valid. I am also able to open this file with firefox, chrome, evince, okular, atril, ghostscript, and Adobe Acrobat, though the mac preview application fails to open the file. My opinion is that there's nothing wrong with mixing xref tables and xref streams, though clearly there are some readers that can't handle it.

It is curious that the file in the referenced qpdf issue qpdf/qpdf#1148 has /Prev pointing to white space preceding the original startxref from the file prior to being appended, but that's not technically incorrect.

2024-02-12 13:30 UTC, jberkenbilt commented
(My opinion, not that it's relevant here since I'm an outsider, is that it would be better not to mix and match.)

2024-02-13 10:48 UTC, Snuffleupagus approved these changes
This is slightly complicated code, but I think it makes sense (and the updated patch is *much* easier to follow.)

r=me, thank you!

2024-02-13 13:45 UTC, merged