Fix Issue 18099
mozilla/pdf.js pull request #18390
Opened 2024-07-04 20:14 UTC by alexcat3

Modifies partialEvaluator.readToUnicode() to handle toUnicode cMaps that omit leading zeros in hex encoded UTF-16, as seen in the PDF in [https://github.com/mozilla/pdf.js/issues/18099](issue 18099). 

In the PDF in question, the toUnicode cmap had a line to map the glyph char codes from 00 to 7F to the corresponding unicode code points. The syntax to map a range of char codes to a range of unicode code points is 
<start_char_code> <end_char_code> <start_unicode_codepoint>
As the unicode code points are supposed to be given in UTF 16, the PDF's line SHOULD have probably read
<00> <7F> <0000>
Instead it omitted two leading zeros from the UTF 16 like this
<00> <7F> <00>
This confused pdf.js into mapping these character codes to the UTF-16 characters with the corresponding high bytes ( 01 becomes \u0100, 02 becomes \u0200) which ended up turning latin text in the PDF into chinese when it was copied.

I'm not sure if the specification actually allows PDFs to do this, but since there's at least one PDF in the wild that does and other PDF readers read it correctly, pdf.js should probably support this.

2024-07-04 20:57 UTC, calixteman commented
Could you add a unit test ? something similar to:
https://github.com/mozilla/pdf.js/blob/790470c1aadf4dc6c4e8ff00364b87ecea4d7bd7/test/unit/api_spec.js#L3202-L3216
You can just test that the retrieved text starts with `Yýsledková listina přijímacích zkoušek`.

2024-07-04 20:58 UTC, alexcat3 commented
OK, I will.

2024-07-04 21:44 UTC, Snuffleupagus reviewed
When addressing the comments, please remember to [squash the commits](https://github.com/mozilla/pdf.js/wiki/Squashing-Commits).

2024-07-04 21:44 UTC, Snuffleupagus commented on test/pdfs/issue18099_reduced.pdf
It seems that this PDF document has a broken XRef table, given that opening it logs: `Warning: Indexing all PDF objects`.
Unless you specifically want to test handling of *corrupt* PDF documents, it's always best if they're valid. So, please run the file through a tool such as e.g. https://github.com/qpdf/qpdf since that should help clean-up the file.

2024-07-04 21:44 UTC, Snuffleupagus commented on test/unit/api_spec.js
> +    it("gets text content, correctly handling documents with toUnicode cmaps that omit leading zeros on hex-encoded UTF-16", async function () {
Please place a blank-line between test-cases to aid readability.
```suggestion
    
    it("gets text content, correctly handling documents with toUnicode cmaps that omit leading zeros on hex-encoded UTF-16", async function () {
```

2024-07-04 21:44 UTC, Snuffleupagus commented on test/unit/api_spec.js
> +    });
All unit-tests should clean-up after themselves, please note the other tests in this file.
```suggestion
      expect(text).toEqual("Hello world!");
      
      await loadingTask.destroy();
    });
```

2024-07-04 21:46 UTC, timvandermeij reviewed
Please squash the commits into one, see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits, once the comment below is addressed. After that this looks good to me, but I'd like to ask @Snuffleupagus or @calixteman to give the final sign-off on this given their familiarity with the font code. Thanks!

2024-07-04 21:46 UTC, timvandermeij commented on test/unit/api_spec.js
> +    it("gets text content, correctly handling documents with toUnicode cmaps that omit leading zeros on hex-encoded UTF-16", async function () {
Please keep a newline between tests, so in this case above `it(...)`, similar to the ones below.

2024-07-05 00:48 UTC, alexcat3 commented on test/pdfs/issue18099_reduced.pdf
Oops, sorry, i'll fix that

2024-07-05 00:49 UTC, alexcat3 commented on test/pdfs/issue18099_reduced.pdf
The pdf was created by hand by me, so that's how it got corrupted.

2024-07-05 07:03 UTC, Snuffleupagus commented on test/pdfs/issue18099_reduced.pdf
Also, please list the filename in https://github.com/mozilla/pdf.js/blob/master/test/pdfs/.gitignore

2024-07-05 17:08 UTC, alexcat3 commented
OK, I made the necessary changes and squashed the commits.

2024-07-05 17:08 UTC, alexcat3 commented on test/pdfs/issue18099_reduced.pdf
Done

2024-07-05 20:15 UTC, timvandermeij commented
The CI failed on linting. You can automatically fix that by running `npx gulp lint --fix` locally. Other than that this patch LGTM, with passing tests which we'll trigger once the linting issue is fixed, but I'll leave the final sign-off here to @Snuffleupagus given the familiarity with the font code. Thanks!

2024-07-06 12:08 UTC, calixteman commented
/botio test

2024-07-06 12:47 UTC, Snuffleupagus requested changes
Can you please improve the *commit message* a bit, such that all relevant information is available on the Git command line as well without having to read GitHub?

Generally the first line of the commit message should contain a summary of the changes, with a reference to the bug/issue, and then any other relevant details below. You included a bunch of nice context in https://github.com/mozilla/pdf.js/pull/18390#issue-2391419810 that belongs in the commit message too. My suggestion would be something like this:
```
Handle toUnicode cMaps that omit leading zeros in hex encoded UTF-16 (issue 18099)

In the PDF in question, the toUnicode cmap had a line to map the glyph char codes from 00 to 7F to the corresponding unicode code points. The syntax to map a range of char codes to a range of unicode code points is
<start_char_code> <end_char_code> <start_unicode_codepoint>
As the unicode code points are supposed to be given in UTF 16, the PDF's line SHOULD have probably read
<00> <7F> <0000>
Instead it omitted two leading zeros from the UTF 16 like this
<00> <7F> <00>
This confused PDF.js into mapping these character codes to the UTF-16 characters with the corresponding high bytes ( 01 becomes \u0100, 02 becomes \u0200) which ended up turning latin text in the PDF into chinese when it was copied.

I'm not sure if the specification actually allows PDFs to do this, but since there's at least one PDF in the wild that does and other PDF readers read it correctly, PDF.js should probably support this.
```

2024-07-06 15:40 UTC, alexcat3 commented
I changed the commit message

2024-07-06 16:56 UTC, Snuffleupagus approved these changes
r=me, thank you!

2024-07-06 16:57 UTC, merged

2024-07-06 17:18 UTC, alexcat3 commented
Thank YOU for all your help!