Implement Text Wrapping and Resizing for FreeText Annotations
mozilla/pdf.js pull request #18447
Opened 2024-07-17 13:07 UTC by shivansh84ya

Description:
This PR introduces enhancements to the FreeTextAnnotationElement to ensure that text within the annotation wraps correctly.

Changes:

CSS Adjustments:
- Added overflow-wrap: break-word and white-space: pre-wrap to ensure text wrapping.
- Enabled resizing with resize: both.
- Applied box-sizing: border-box for consistent sizing with padding and borders.

JavaScript Enhancements:
- Updated the FreeTextAnnotationElement class:
   - Ensured text content wraps correctly within the container.
   - Added _addResizeHandles and _addResizeListeners methods to enable and handle resizing of the annotation box.
   - Listened for zoom changes and applied scaling to maintain proper layout and functionality.
- Included event listeners to manage resize events and cleanup to avoid memory leaks.

Testing:
- Verified that the text wraps correctly when the annotation box is resized.
- Ensured that resizing handles appear and function as expected.
- Confirmed that zoom functionality scales the annotation correctly.

2024-07-17 13:21 UTC, Snuffleupagus requested changes

2024-07-17 13:21 UTC, Snuffleupagus commented on src/display/annotation_layer.js
Given that the issue is regarding FreeText-editing, surely the code belongs in https://github.com/mozilla/pdf.js/blob/master/src/display/editor/freetext.js file and not in this file!?

2024-07-17 13:21 UTC, calixteman commented
I just opened test/pdfs/freetexts.pdf with your patch applied, I tried to play with the gray squares and I'm sorry but I don't understand what it's supposed to do. I'm probably missing some context...

2024-07-18 09:11 UTC, shivansh84ya commented
Hello @calixteman,

I have attached a screen recording that demonstrates the intended functionality of the FreeText annotations after applying my patch. Please review it at your convenience. If there are any areas that need improvement, I would appreciate your feedback.
https://github.com/user-attachments/assets/5c782d05-39ab-4ce9-bf1f-882b413f89d8

Thank you!

2024-07-18 09:30 UTC, nicolo-ribaudo commented
> Testing:
> 
>     * Verified that the text wraps correctly when the annotation box is resized.
> 
>     * Ensured that resizing handles appear and function as expected.
> 
>     * Confirmed that zoom functionality scales the annotation correctly.

Can you also test that when saving the PDF and re-opening it, the annotation text still wraps correctly?

2024-07-18 11:27 UTC, shivansh84ya commented
Hi @nicolo-ribaudo,

I appreciate the feedback and I’m currently revising and improving the code to make it proficient as per the requirements. I will also test that when saving the PDF and re-opening it, the annotation text still wraps correctly.

2024-07-18 12:20 UTC, calixteman commented
Ok I managed to do something similar to what you shew in your video.
That said, the box is resized when I try to move the box outside of the page but only on the right !
Once I release the mouse button, the box just gets its original dimensions, so I'm sorry, but I don't understand what's the problem you're trying to solve.

2024-07-18 14:47 UTC, shivansh84ya commented
Hi @calixteman,

To clarify, the primary issue I addressed was ensuring that FreeText annotations wrap text correctly.
Previously, resizing the annotation box caused it to revert to its original size, and there were issues when moving it outside the page boundary. These behaviors have been corrected in my patch.

I have attached before and after screen recordings to demonstrate the resolved issues.
Before: https://github.com/user-attachments/assets/cda44851-ac3c-444e-a99c-95a593989c4d
After: https://github.com/user-attachments/assets/0abb8852-e74e-4401-be70-ac8bfbfa2ff2

Thank you for reviewing this.

2024-07-18 16:35 UTC, shivansh84ya commented on src/display/annotation_layer.js
Hello @Snuffleupagus,

Thank you for pointing that out. I will move the relevant code to src/display/editor/freetext.js as suggested. I appreciate your guidance and will update the PR accordingly.

2024-07-18 16:38 UTC, Snuffleupagus commented on src/display/annotation_layer.js
Also, given that other editors already have resizers (see e.g. the Stamp-editor) there ought to be a lot of existing code/patterns that could *and should* be re-used to avoid having to "re-invent the wheel" so to speak.

2024-07-18 17:33 UTC, shivansh84ya commented on src/display/annotation_layer.js
Hello @Snuffleupagus,

Thank you for the feedback. I will review the existing code for the Ink and Stamp editors to understand their implementation of resizers. I will then update my implementation to reuse these existing patterns and ensure consistency across the codebase.

2024-07-21 17:02 UTC, shivansh84ya commented
> > Testing:
> > ```
> > * Verified that the text wraps correctly when the annotation box is resized.
> > 
> > * Ensured that resizing handles appear and function as expected.
> > 
> > * Confirmed that zoom functionality scales the annotation correctly.
> > ```
> 
> Can you also test that when saving the PDF and re-opening it, the annotation text still wraps correctly?

Hi @nicolo-ribaudo Currently working on ensuring that the annotation text wraps correctly when saving and re-opening the PDF. Actively troubleshooting and seeking solutions to resolve these issues. Once the issue is resolved, I plan to raise a PR for the changes.

2025-01-19 08:06 UTC, closed without merging