[Editor] Avoid to have a selected stamp annotation on top of the secondary toolbar (bug 1911980)
mozilla/pdf.js pull request #18793
Opened 2024-09-25 15:17 UTC by calixteman

And I changed the permissions on the images to remove the `x` flag which is useless.

2024-09-25 15:17 UTC, calixteman commented
/botio integrationtest

2024-09-25 16:09 UTC, Snuffleupagus requested changes
*Pretty please test these sort of changes affecting the viewer more thoroughly during development, to save my time have to re-review stuff.*

2024-09-25 16:20 UTC, Snuffleupagus commented on web/viewer.css
If this is the only regression, maybe changing the colour to `transparent` here could work?
https://github.com/mozilla/pdf.js/blob/9735a840ad9e8b6f87d24279504400f6da13acfe/web/viewer.css#L303

2024-09-25 16:33 UTC, calixteman commented
I'm using the dark mode and this kind of difference is almost invisible for me.

That said, it's unrelated to this patch but I think the sidebar should live either under the toolbar or just after it, because if the user clicks or <enter> on the toggle sidebar button and then hit <tab> then the focus is moving on the toolbar, then the pages, then the firefox ui and finally the sidebar.
In Edge, the focus moves on the sidebar when in Chrome it moves on the toolbar and then on the sidebar.
I'll file a bug and see what the a11y team thinks about that.

2024-09-25 17:19 UTC, calixteman commented on web/viewer.css
I finally let the border as it is and  changed the z-index: there was a regression with the find popup too.

2024-09-25 17:57 UTC, Snuffleupagus commented on web/viewer.css
And now the sidebar is broken when the viewer is narrow, since it's no longer "above" the document as intended; all these z-index changes start to feel really risky!

![sidebar](https://github.com/user-attachments/assets/8d3d8e4a-9d72-4596-9da4-d3b979133c09)

2024-09-26 13:59 UTC, calixteman commented
I think it should safe: finally the patch just changes the current z-index values we've but in keeping the same order and just add a new one for the viewer container to make sure it's behind the sidebar and the toolbar.

2024-09-26 14:15 UTC, Snuffleupagus commented
Should we perhaps *also* implement the suggestion from https://github.com/mozilla/pdf.js/pull/18793#discussion_r1775536763, although not technically needed here,  since having a hard-coded colour seems generally wrong?

2024-09-26 17:19 UTC, Snuffleupagus commented
/botio-linux preview

2024-09-26 17:49 UTC, Snuffleupagus approved these changes
r=me, hopefully we've found all regressions now; thank you.

2024-09-26 18:16 UTC, merged