[api-minor] Add support for relative URLs, in both annotations and the outline, by adding a `docBaseUrl` parameter to `PDFJS.getDocument` (bug 766086)
mozilla/pdf.js pull request #7689
Opened 2016-10-04 10:54 UTC by Snuffleupagus

*Please refer to the individual commit messages.*

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=766086.
(*Note:* This PR attempts to implement https://github.com/mozilla/pdf.js/pull/7212#issuecomment-216678039, hence it supersedes that one.)

2016-10-04 10:56 UTC, Snuffleupagus commented
/botio unittest

2016-10-05 15:23 UTC, Snuffleupagus commented
/botio unittest

2016-10-09 16:04 UTC, Snuffleupagus commented
/botio-linux preview

2016-10-10 10:10 UTC, Snuffleupagus commented
/botio unittest

2016-10-15 15:46 UTC, yurydelendik commented
I like that we can pass base URI of the document. I wonder if make page object referring its document and annotation object referring its page will allow us avoid passing base URI to the other API functions, e.g. annotation.page.document.baseUrl might be more easier to maintain.

2016-10-15 19:05 UTC, Snuffleupagus commented
> I like that we can pass base URI of the document. I wonder if make page object referring its document and annotation object referring its page will allow us avoid passing base URI to the other API functions, e.g. annotation.page.document.baseUrl might be more easier to maintain.

Thank you for the feedback!
I'm not sure that I completely understand your preferred changes, but after looking through the code a bit it seems to me that adding `docBaseUrl` (only) to `PDFManager` may very well be the cleanest solution.
Doing this removes the need to pass a single parameter around, and we already have access to a `PDFManager` instance in both `PDFDocument` and `Page`, which should reduce the maintenance burden.
As far as I can see, we still need to pass *something* in when creating the Annotations, but with this now being a `PDFManager` instance it should at least be better than previously.

I'm hoping that the updated PR is more what you had in mind, but please let me know otherwise!

*Note:* I added a new WIP commit with the above changes, and I'll fold it into the previous commit once the PR is ready to land.

2016-10-18 14:05 UTC, yurydelendik requested changes
Looks good so far. I need to review  Catalog.parseDestDictionary in details.

2016-10-18 15:09 UTC, Snuffleupagus commented on src/main_loader.js
> -  exports.isValidUrl = sharedUtil.isValidUrl;
Very good point, thanks for spotting this!
I've added a `isValidUrl` function as suggested in `display/dom_utils.js`.

2016-10-19 18:43 UTC, yurydelendik approved these changes
Looks good with the requested changes.

2016-10-19 18:43 UTC, yurydelendik commented on src/core/obj.js
> +          } else if (urlDict) {
We lost `isString(urlDict)` here. Below we expect it to be a string (it can be array or other type).

2016-10-19 18:43 UTC, yurydelendik commented on src/core/obj.js
> +        resultObj.unsafeUrl = url.toString();
Let's have resultObj.unsafeUrl regardless `absoluteUrl` result.

Also `url` must a string (in  the `if (url) {`)

2016-10-19 18:43 UTC, yurydelendik commented on src/core/obj.js
> +      resultObj.dest = isName(dest) ? dest.name : dest;
Shall we ensure that `dest` is a string here (in the `!isName(dest)` branch)?

2016-10-19 18:43 UTC, yurydelendik commented on src/core/obj.js
> +          } else if (url) {
I'm thinking we need to ensure url is a string here?

2016-10-19 20:17 UTC, Snuffleupagus commented
Comments have been addressed, thank you for the review!
Besides updated/improved unit-tests, the only functional changes were made in the second commit, and to simplify auditing them I'm including the diff below:
```diff
diff --git a/src/core/obj.js b/src/core/obj.js
index 2e0b607..bbbfe23 100644
--- a/src/core/obj.js
+++ b/src/core/obj.js
@@ -594,7 +594,7 @@ var Catalog = (function CatalogClosure() {
   Catalog.parseDestDictionary = function Catalog_parseDestDictionary(params) {
     // Lets URLs beginning with 'www.' default to using the 'http://' protocol.
     function addDefaultProtocolToUrl(url) {
-      if (isString(url) && url.indexOf('www.') === 0) {
+      if (url.indexOf('www.') === 0) {
         return ('http://' + url);
       }
       return url;
@@ -629,7 +629,7 @@ var Catalog = (function CatalogClosure() {
           if (isName(url)) {
             // Some bad PDFs do not put parentheses around relative URLs.
             url = '/' + url.name;
-          } else if (url) {
+          } else if (isString(url)) {
             url = addDefaultProtocolToUrl(url);
           }
           // TODO: pdf spec mentions urls can be relative to a Base
@@ -646,7 +646,7 @@ var Catalog = (function CatalogClosure() {
             // We assume that we found a FileSpec dictionary
             // and fetch the URL without checking any further.
             url = urlDict.get('F') || null;
-          } else if (urlDict) {
+          } else if (isString(urlDict)) {
             url = urlDict;
           }
 
@@ -686,12 +686,13 @@ var Catalog = (function CatalogClosure() {
         default:
           warn('Catalog_parseDestDictionary: Unrecognized link type "' +
                linkType + '".');
+          break;
       }
     } else if (destDict.has('Dest')) { // Simple destination link.
       dest = destDict.get('Dest');
     }
 
-    if (url) {
+    if (isString(url)) {
       url = tryConvertUrlEncoding(url);
       var absoluteUrl;
       try {
@@ -700,12 +701,16 @@ var Catalog = (function CatalogClosure() {
 
       if (isValidUrl(absoluteUrl, /* allowRelative = */ false)) {
         resultObj.url = absoluteUrl;
-      } else {
-        resultObj.unsafeUrl = url.toString();
       }
+      resultObj.unsafeUrl = url;
     }
     if (dest) {
-      resultObj.dest = isName(dest) ? dest.name : dest;
+      if (isName(dest)) {
+        dest = dest.name;
+      }
+      if (isString(dest) || isArray(dest)) {
+        resultObj.dest = dest;
+      }
     }
   };

```

2016-10-19 20:17 UTC, Snuffleupagus commented
/botio unittest

2016-10-19 20:25 UTC, yurydelendik approved these changes

2016-10-19 20:51 UTC, merged