SVG: group creation refactoring and optimizations
mozilla/pdf.js pull request #7715
Opened 2016-10-12 20:25 UTC by timvandermeij

The commit messages contain more information about the changes.

2016-10-15 14:23 UTC, yurydelendik requested changes
That is a really good start. I think we need to backout some changes in the viewer and avoid a regression in chrome.

2016-10-15 14:23 UTC, yurydelendik commented on src/display/svg.js
> +        this.svg.setAttributeNS(null, 'transform', pm(viewport.transform));
this does not work for chrome -- we will need to create a root group and use it as this.svg ?

2016-10-15 14:23 UTC, yurydelendik commented on src/display/svg.js
> +    _finishGroup: function SVGGraphics_finishGroup() {
_finishGroup can be removed, see https://github.com/yurydelendik/pdf.js/commit/f4c8099678a0d19f1e48c891aa55c2581931495f

2016-10-15 20:15 UTC, timvandermeij commented
I have updated the commits based on the review comments.

2016-10-15 20:16 UTC, timvandermeij commented on src/display/svg.js
> +        this.svg.setAttributeNS(null, 'transform', pm(viewport.transform));
Fixed in the new commits.

2016-10-15 20:16 UTC, timvandermeij commented on src/display/svg.js
> +    _finishGroup: function SVGGraphics_finishGroup() {
Fixed in the new commits. Nice find!

2016-10-17 15:10 UTC, yurydelendik approved these changes
Thank you for the patch.

2016-10-17 15:10 UTC, merged