disable range request in iPhone
mozilla/pdf.js pull request #7824
Opened 2016-11-17 16:44 UTC by godwin668

Better way but NOT necessarily best way to solve the IOS webview APP error: Unexpected server response (206) while retrieving PDF...

Details:
1. At the beginning, I only found the Error in IOS WeChat APP, so I solved it by checking WeChat:
https://github.com/godwin668/pdf.js/commit/9ad57d4ad5c03a33f637da5f8fd3ede3c4c7f39a

2. But I found this error in other IOS app, so I checked UA details of them as follow:

a) iPhone WeChat APP UserAgent (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 MicroMessenger/6.3.30 NetType/WIFI Language/zh_CN

b) iPhone Other APP UserAgent (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 QYZone

Maybe all webview app in IOS 10 have this problem, and since Safari & Chrome in IOS also does NOT support range request in IOS, so I think it's a better way to disable range request in iPhone by this regex:
var isIPhone = /iPhone/.test(navigator.userAgent);
if (isIPhone) {
    PDFJS.disableRange = true;
    PDFJS.disableStream = true;
}

solve issues:
https://github.com/mozilla/pdf.js/issues/7815
https://github.com/mozilla/pdf.js/issues/7754
https://github.com/mozilla/pdf.js/pull/7800

2016-11-17 16:59 UTC, Snuffleupagus commented
Wouldn't the same problem apply to e.g. iPads as well?

2016-11-17 16:59 UTC, Snuffleupagus commented on web/compatibility.js
> +
Trailing whitespace on this line.

2016-11-19 10:39 UTC, Snuffleupagus requested changes
Wouldn't the same problem apply to e.g. `iPad`s as well?

Also, as mentioned in http://stackoverflow.com/questions/9038625/detect-if-device-is-ios: just checking for `iPhone` can incorrectly match some versions of Internet Explorer too, which we should avoid.

2016-11-21 14:10 UTC, godwin668 commented
@Snuffleupagus

I tested on iPad & iPhone respectively with following result:

------------------------
-- iPad test UserAgent
------------------------
iPad Safari (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Version/9.0 Mobile/13G35 Safari/601.1

iPad Chrome (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)CriOS/54.0.2840.91 Mobile/13G35 Safari/601.1.46

iPad QQ APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 IPadQQ/6.3.1.5 QQ/6.3.1.5

iPad WeChat APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 MicroMessenger/6.3.25 NetType/WIFI Language/zh_CN

------------------------
-- iPhone test UserAgent
------------------------
iPhone WeChat APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 MicroMessenger/6.3.30 NetType/WIFI Language/zh_CN

iPhone Other APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 QYZone

2016-11-21 14:21 UTC, godwin668 commented
@Snuffleupagus

I tested on iPad & iPhone respectively with following result:

------------------------
-- iPad test UserAgent
------------------------
iPad Safari (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Version/9.0 Mobile/13G35 Safari/601.1

iPad Chrome (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)CriOS/54.0.2840.91 Mobile/13G35 Safari/601.1.46

iPad QQ APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 IPadQQ/6.3.1.5 QQ/6.3.1.5

iPad WeChat APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 MicroMessenger/6.3.25 NetType/WIFI Language/zh_CN

------------------------
-- iPhone test UserAgent
------------------------
iPhone WeChat APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 MicroMessenger/6.3.30 NetType/WIFI Language/zh_CN

iPhone Other APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 QYZone

2016-11-21 14:22 UTC, godwin668 commented
@Snuffleupagus

I tested on iPad & iPhone respectively with following result:

------------------------
-- iPad test UserAgent
------------------------
iPad Safari (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Version/9.0 Mobile/13G35 Safari/601.1

iPad Chrome (OK)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)CriOS/54.0.2840.91 Mobile/13G35 Safari/601.1.46

iPad QQ APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 IPadQQ/6.3.1.5 QQ/6.3.1.5

iPad WeChat APP (Fail)
Mozilla/5.0(iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46(KHTML, like Gecko)Mobile/13G35 MicroMessenger/6.3.25 NetType/WIFI Language/zh_CN

------------------------
-- iPhone test UserAgent
------------------------
iPhone WeChat APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 MicroMessenger/6.3.30 NetType/WIFI Language/zh_CN

iPhone Other APP (Fail):
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 QYZone

2016-11-21 14:22 UTC, yurydelendik commented
@godwin668 how about `/\b(iPhone|iPad)(?=;)/.test(...)` ?

2016-11-21 14:26 UTC, Snuffleupagus commented
> @godwin668 how about `/\b(iPhone|iPad)(?=;)/.test(...)` ?

Based on the discussion in http://stackoverflow.com/questions/9038625/detect-if-device-is-ios/9039885#9039885, it might be more complete to do something like this instead:
```
var iOS = /\b(iPhone|iPad|iPod)(?=;)/.test(navigator.userAgent) && !window.MSStream;
```

2016-11-21 14:27 UTC, yurydelendik commented
I don't think we need window.MSStream

2016-11-22 21:57 UTC, timvandermeij commented
Superseded by #7841.

2016-11-22 21:57 UTC, closed without merging