Expand allowed pdf.worker.js load methods
mozilla/pdf.js pull request #7866
Opened 2016-12-03 17:17 UTC by matt-curtis

Allows for `pdf.worker.js` to be included in the page by `<script>` or other means, and eliminates unnecessary requests for it.

2016-12-03 17:51 UTC, matt-curtis commented
Hmm, that's still longer than required. What's the recommended approach here for shortening a line? Is splitting the assignment over two lines acceptable? Not sure I see it mentioned in the Style Guide.

2016-12-04 19:00 UTC, yurydelendik requested changes
window or window.pdfjsDistBuildPdfWorker can be undefined. It's not clear how entire logic will work if pdf.worker.js is not included in scripts.

Looks like it's incomplete replacement for pdf.combined.js. I don't think we want to support both this solution and .combined.js to avoid sub-par performance use case

2016-12-04 20:44 UTC, matt-curtis commented
@yurydelendik What is `pdf.combined.js`? I'm not seeing it mentioned anywhere - have I missed it?

Also, in cases of `window` being `null` or `pdfjsDistBuildPdfWorker` being `null` wouldn't a simple `if(window && window.pdfjsDistBuildPdfWorker)` suffice? Thanks for reviewing.

2016-12-04 22:03 UTC, yurydelendik commented
> What is pdf.combined.js? I'm not seeing it mentioned anywhere - have I missed it?

It combined pdf.js and pdf.worker.js file, but we don't recommend of using it since pdf.worker.js shall not be loaded in the main thread (pdf.worker.js is loaded via script only for legacy browsers were using web workers are possible). Loading pdf.worker.js in the main thread degrade performance of the pdf.js.

2016-12-04 22:29 UTC, matt-curtis commented
I see. My case might be rare - I *want* `pdf.js`/`pdf.worker.js` to do their work on the main thread. I can understand if loading `pdf.worker.js` on the main thread is not desired in the majority of cases, but it doesn't hurt and is fairly trivial to include the possibility, no?

2016-12-05 14:51 UTC, Snuffleupagus commented
@matt-curtis Without knowing your specific use case; couldn't you simply use the already existing `pdf.combined.js` file instead?

If you're building PDF.js yourself, you'd use the `gulp singlefile` build target to create the `pdf.combined.js` file. Or if you want a pre-built version, it can be found in the https://github.com/mozilla/pdfjs-dist repository, please see https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.combined.js.

2016-12-05 16:27 UTC, matt-curtis commented
@Snuffleupagus That's exactly what I need, I wasn't aware of the distribution repo. Where is it documented? Thank you! Closing this.

2016-12-05 16:27 UTC, closed without merging

2016-12-06 11:35 UTC, Snuffleupagus commented
> Where is it documented?

It's mentioned in the FAQ, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#is-there-a-pre-built-version-pdfjs-available.