Document: handle indirect objects in `MediaBox` and `CropBox` entries
mozilla/pdf.js pull request #7873
Opened 2016-12-05 23:54 UTC by timvandermeij

This patch makes sure that when we fetch `MediaBox` and `CropBox` entries that they do not contain indirect objects. Previously these were not fetch, causing other rendering code to fail. To ensure that this happens in a similar way for both entries, we extract the `CropBox` fetching and validation code into a getter, just like we already had for `MediaBox`, and make them as similar as possible (and rename vague names such as `obj`). The advantage of the getter is that the code for `MediaBox` and `CropBox` validation is now similar and extracted, making the `view` getter simpler as well.

Fixes #7872.

@Snuffleupagus Could you perhaps review this? I'm also not sure about testing this. We can add the original file as a linked test case, but a reduced test case would be better. Do you have ideas for creating such a reduced test case? I don't know how to craft them myself. I think it can be just an ordinary PDF with one line of text, but where the `cropBox`/`mediaBox` entries contain indirect objects. Thank you in advance for helping out here!

2016-12-06 00:06 UTC, timvandermeij commented
/botio-linux preview

2016-12-06 09:27 UTC, Snuffleupagus requested changes
To be totally honest, I'm imagining a much simpler and more general solution here. (Since this issue may happen again in the future if support for other "array" parameters are added).
My thinking is something like https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-7872 instead, and a reduced test-case ~should be~ is easy to create here.
Should I submit a PR with that change, and a test-case included?

2016-12-06 21:37 UTC, timvandermeij commented
I think that's a nice solution as well. The only thing I think makes sense is to create the `CropBox` getter as in this PR because it brings it more in line with the other page properties (most notably the `MediaBox` getter that we already have, and the recently added `UserUnit`). It will also make it easier to expose via e.g., the API later on, and it makes the `view` getter less cluttered with crop box sanitizing code it shouldn't really need to worry about.

That being said, I do like your solution of not including the `for` loops in each getter and amending the `getInteritedPageProp` method instead (and of course the reduced test case). How about creating two commits in this PR, the first one being your commit (that fixes the issue) and the second one being my commit without the `for` loops and length variables? My commit will then be much shorter, but we would still have the getter/name improvements.

2016-12-07 10:26 UTC, Snuffleupagus commented
> The only thing I think makes sense is to create the CropBox getter as in this PR because it brings it more in line with the other page properties (most notably the MediaBox getter that we already have, and the recently added UserUnit). It will also make it easier to expose via e.g., the API later on, and it makes the view getter less cluttered with crop box sanitizing code it shouldn't really need to worry about.

That's a fair point, but I've got one small reservation: This would require us to *always* compute the intersection, since then `get cropBox()` will always be defined. Could we skip doing that if `cropBox === mediaBox` to avoid what will often be a useless `Util.intersect` call? If so, I'm OK with it :-)

2016-12-07 20:52 UTC, timvandermeij commented
Yes, I think that should be possible. I'll update the PR soon.

2016-12-08 21:36 UTC, timvandermeij commented
/botio-linux preview

2016-12-08 21:38 UTC, Snuffleupagus approved these changes
Thank you!
r=me, with nits, assuming that the tests pass of course!

**Edit:** Obviously I cannot review my own patch, but yours look good :-)

2016-12-08 21:38 UTC, Snuffleupagus commented on src/core/document.js
> +      return shadow(this, 'view', !intersection ? mediaBox : intersection);
Nit: It would probably suffice to just check `intersection || mediaBox` here, instead of the ternary condition.

2016-12-08 21:38 UTC, Snuffleupagus commented on src/core/document.js
> +
Nit: I'm not sure if we need this newline for readability, let's make the diff smaller instead :-)

2016-12-08 21:48 UTC, timvandermeij commented on src/core/document.js
> +      return shadow(this, 'view', !intersection ? mediaBox : intersection);
Fixed in the new commit.

2016-12-08 21:49 UTC, timvandermeij commented
/botio-linux preview

2016-12-08 21:55 UTC, timvandermeij commented
/botio test

2016-12-08 22:24 UTC, timvandermeij commented
/botio makeref

2016-12-08 22:59 UTC, timvandermeij commented
Even though the message has not been posted, the Linux bot finished successfully. Merging with r=me for @Snuffleupagus' commit.

2016-12-08 22:59 UTC, merged