Update evaluator.js -> Proposal to split words for getTextContent layer
mozilla/pdf.js pull request #8103
Opened 2017-02-24 08:45 UTC by Helidium

Changed the way text extraction treats words. Now it extracts word by word, so text selection or markup are more properly alligned. Please review the proposal as it is assuming splitSpaces variable to be set to true, it should be passed through options. This is a quick hack, probably a better solution exists.

Thank you for your time,

2017-02-24 09:03 UTC, Helidium reviewed
Fixed travis errors

2017-02-24 09:30 UTC, Snuffleupagus requested changes
In order to improve the UX of text-selection, we've gone to great lengths to try and combine separate pieces of text (see e.g. #6590 and #7337). As-is this patch will result in a *significantly* worse text-selection experience, not to mention that it'll fail a lot of existing tests.

It's not *at all* clear what the purpose of this patch is, since there first of all are no test-case(s) included and second of all no actual explanation of *why* you want/need this behaviour (I'm assuming it's for a custom PDF.js implementation).

2017-02-24 09:51 UTC, Helidium commented
I have made this patch, beacuse in situations with long lines of text, the words in the middle are not aligned properly. The missalignment is visible for example here #6636. I will prepare the before / after images that explain the situation.

2017-02-24 10:46 UTC, Helidium commented
Here are the promised before / after screens:
![before](https://cloud.githubusercontent.com/assets/1107636/23300672/e711a70a-fa86-11e6-8889-3687cb5417df.jpeg)
![after](https://cloud.githubusercontent.com/assets/1107636/23300674/ed932cc0-fa86-11e6-9d31-57625902bac3.jpeg)

2017-02-24 10:52 UTC, Helidium reviewed
Additional check before addFakeSpaces

2017-02-24 11:36 UTC, Helidium reviewed
Travis build fix

2017-03-01 19:17 UTC, Helidium commented
Any updates on this? Is there something else you need @Snuffleupagus ?

2017-03-03 04:50 UTC, yurydelendik commented
> Any updates on this? Is there something else you need @Snuffleupagus ?

Can you provide information of about how many divs before and after your change?

2017-09-25 20:26 UTC, timvandermeij commented
Closing since we cannot merge this in the current state. Important information like impact on performance and how this affects the UX for text selection is missing.

2017-09-25 20:26 UTC, closed without merging