Fix svg image render
mozilla/pdf.js pull request #8350
Opened 2017-04-28 09:08 UTC by ydfzgyj

Official example to use pdf2svg force all images export as png and object url from Blob, but in node.js, it won't work, so I try to fix some places in this example:
1. Force generate a base64 string when analyze image stream
2. If image type is jpeg, export it directly maybe better than transform to a png image
3. add a fake `Image` object in node.js environment

Because read image size when load jpeg stream is too complex, `width` and `height` of image in `paintJpegXObject` was replaced by `w` and `h` readed from args

2017-04-28 19:35 UTC, yurydelendik commented
Will that stub work for JpegDecode task at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L1760 ?

2017-05-01 16:19 UTC, ydfzgyj commented
> Will that stub work for JpegDecode task at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L1760 ?

I'm afraid not... JpegDecode task need to create a temp canvas DOM to transform data, it's too complex unless import other packages like node-canvas...
So it will cause error when image has mask but I hadn't notice it before, Maybe I can fix it by add a limitation in `NativeImageDecoder.isDecodable`, but I'm not sure if it's a good idea

2017-05-01 16:33 UTC, Snuffleupagus commented
I'm not entirely certain that I understand what issue this PR attempts to solve, but `disableNativeImageDecoder` definitely needs to be set to avoid issues when dealing with JPEG images in Node.js (since it lets the PDF.js built-in JPEG decoder handle the image).

The SVG example works fine for me when run against the current `master`, since the `Blob` requirement was a temporary issue that was fixed by PR #8346 (in response to issue #8344, which contains a test-case that this PR would break).

Since this PR was based on an now outdated version of PDF.js, are these issues still present in the *latest* PDF.js `master` branch?

2017-05-01 17:29 UTC, ydfzgyj commented
> I'm not entirely certain that I understand what issue this PR attempts to solve, but disableNativeImageDecoder definitely needs to be set to avoid issues when dealing with JPEG images in Node.js (since it lets the PDF.js built-in JPEG decoder handle the image).

@Snuffleupagus If we set `disableNativeImageDecoder`, JPEG images will be exported as PNGs, but that's too large.
https://github.com/mozilla/pdf.js/blob/master/src/core/evaluator.js#L471
Because codes here can directly add JPEG images to opList, we only need to set `disableCreateObjectURL = true` to ensure these images export as base64 strings.

I have tried sample pdf in #8344, this PR works well for me. I'm not sure if there are any conflicts with latest `master` branch, I think I need to have more tests.

2017-05-01 18:14 UTC, yurydelendik commented
Can you try https://downloads.globalchange.gov/usimpacts/pdfs/climate-impacts-report.pdf ? (I think page 2)

2017-05-01 18:21 UTC, yurydelendik commented
More simple test case http://itp.usc.edu/uploads/About_Stacks.pdf

2017-05-01 18:33 UTC, ydfzgyj commented
@yurydelendik page 3 will throw a warning
> Warning: Unable to decode image: TypeError: tmpCanvas.getContext is not a function

svg can still be generated, but the image which causes warning is missing

I tried to force `NativeImageDecoder.isDecodable` return false in node.js environment, it was working well. But I worry about whether it will affect canvas mode.

2017-05-03 15:04 UTC, yurydelendik requested changes
Add nativeImageDecoderSupport parameter and deprecate disableNativeImageDecoder in following way (false => nativeImageDecoderSupport's 'decode', true => 'none'). The nativeImageDecoderSupport will default to 'decode'. For the pdf2svg example the value will be set to 'display'.

2017-05-03 15:04 UTC, yurydelendik commented on examples/node/domstubs.js
> +Image.prototype.__defineSetter__('src', function (val) {
Use Object.defineProperty or object literal getter instead.

2017-05-03 15:04 UTC, yurydelendik commented on examples/node/pdf2svg.js
> +pdfjsLib.PDFJS.disableCreateObjectURL = true
We are using forceDataSchema in SVGGraphics. Why we need disableCreateObjectURL ?

2017-05-03 15:04 UTC, yurydelendik commented on examples/node/pdf2svg.js
> -  disableNativeImageDecoder: true,
Looks like disableNativeImageDecoder shall be replaced by different mode, e.g. nativeImageDecoderSupport = (none|store|decode)

2017-05-04 22:38 UTC, yurydelendik approved these changes
Looks really good. Good to go with addressed comments and squashed commits.

2017-05-04 22:38 UTC, yurydelendik commented on examples/node/domstubs.js
> +  Object.defineProperty(this, 'src', {
change it to
```
function Image() {
  this._src = null;
  this.onload = null;
}
Image.prototype = {
  get src() { return this._src; }
  set src(value) { .... }
};
```

2017-05-04 22:38 UTC, yurydelendik commented on src/display/api.js
> +    params.nativeImageDecoderSupport !== 'display') {
Use `NativeImageDecoding` enum here and export from api/pdf.js

2017-05-04 22:38 UTC, yurydelendik commented on src/core/evaluator.js
> +    nativeImageDecoderSupport: 'decode',
Add `NativeImageDecoding` "enum" to src/shared/util.js and use NativeImageDecoding.DECODE (which will be equal to 'decode') here.

2017-05-05 08:48 UTC, Snuffleupagus reviewed
I've left a couple of comments with suggestions of improved wording in comments, and also some formatting/naming issues.

2017-05-05 08:48 UTC, Snuffleupagus commented on examples/node/pdf2svg.js
> +  // Try to export JPEG directly if don't need canvas to decode images
Nit: This comment reads a little strangely, I'd suggest e.g. `Try to export JPEG images directly if they don't need any further processing.` instead.

2017-05-05 08:48 UTC, Snuffleupagus commented on src/core/evaluator.js
> +      var useNativeImageDecoder = this.options.nativeImageDecoderSupport;
This variable name is now misleading, please change it to `var nativeImageDecoderSupport` instead.

2017-05-05 08:48 UTC, Snuffleupagus commented on src/core/evaluator.js
> +      if (useNativeImageDecoder !== 'none' &&
With the comments above taken into account, this line should be:
`if (nativeImageDecoderSupport !== NativeImageDecoding.NONE &&`

2017-05-05 08:48 UTC, Snuffleupagus commented on src/core/evaluator.js
> +      if (useNativeImageDecoder === 'decode' &&
With the comments above taken into account, this line should be:
`if (nativeImageDecoderSupport === NativeImageDecoding.DECODE &&`

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> +  if ('disableNativeImageDecoder' in params) {
Nit: `if (params.disableNativeImageDecoder !== undefined) {`.

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> +      'need either `decode`, `none` or `display`');
Nit: Let's use regular quotes here, e.g.
```
warn('Invalid parameter nativeImageDecoderSupport, ' +
      'need either "decode", "none" or "display".');
```

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> +    params.nativeImageDecoderSupport !== 'display') {
Nit: Please also remember to align the lines correctly in an `if` statement.

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> +    params.nativeImageDecoderSupport = 'decode';
With comments above taken into account, this line should be:
`params.nativeImageDecoderSupport = NativeImageDecoding.DECODE;`

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> + *   images as much as possible, see more in `examples/node/pdf2svg.js`.
The wording/grammar can probably be improved here, and I don't think that the API documentation should refer to a *specific* example file; e.g. something like this:
```
* @property {string} nativeImageDecoderSupport - (optional) Strategy for
*   decoding certain (simple) JPEG images in the browser. This is useful for
*   environments without DOM image and canvas support, such as e.g. Node.js.
*   Valid values are 'decode', 'display' or 'none'; where 'decode' is intended
*   for browsers with full image/canvas support, 'display' for environments
*   with limited image support through stubs (useful for SVG conversion),
*   and 'none' where JPEG images will be decoded entirely by PDF.js.
*   The default value is 'decode'.
```

2017-05-05 08:48 UTC, Snuffleupagus commented on src/display/api.js
> + * @property {string} nativeImageDecoderSupport - (optional) Strategy when
Nit: I'm now wondering if it wouldn't suffice to just use the shorter `nativeImageDecoding` name here (and everywhere else in the patch)?

2017-05-05 09:20 UTC, ydfzgyj commented
@yurydelendik I'm not sure if I understand your request correctly... the code looks a little weird, I'll squash commits until the code is acceptable.

2017-05-05 09:33 UTC, ydfzgyj commented on src/display/api.js
> + *   images as much as possible, see more in `examples/node/pdf2svg.js`.
Sorry for my poor English 😅

2017-05-05 10:30 UTC, Snuffleupagus commented on src/pdf.js
> +exports.NativeImageDecoding = pdfjsSharedUtil.NativeImageDecoding;
This needs a similar entry in added in https://github.com/mozilla/pdf.js/blob/master/src/main_loader.js as well.

2017-05-05 10:31 UTC, Snuffleupagus commented on src/shared/util.js
> +var NativeImageDecoding = {
Nit: Let's make this `const` instead.

2017-05-05 10:35 UTC, Snuffleupagus commented on src/display/api.js
> + * @property {string} nativeImageDecoderSupport - (optional) Strategy for
As asked in https://github.com/mozilla/pdf.js/pull/8350#discussion_r114952873, can we use the slightly more compact `nativeImageDecoding` name here (and elsewhere in the patch)?

2017-05-09 14:37 UTC, yurydelendik commented
/botio test

2017-05-09 15:53 UTC, merged

2017-05-09 15:53 UTC, yurydelendik commented
Thank you for the patch.

2018-03-21 16:27 UTC, svenyonson commented
@yurydelendik - This is still failing for me. I added `PDFJS.disableNativeImageDecoder = true;` but still get this error:
Warning: Native JPEG decoding failed -- trying to recover: Image is not defined

Versions:
    "pdfjs": "^2.0.0-alpha.3",
    "pdfjs-dist": "^2.0.398",

StackOverflow issue: (before adding .disableNativeImageDecoder)
https://stackoverflow.com/questions/49375424/image-is-not-defined-error-when-extracting-images-using-node-js-and-pdf-js