Adds gulp dist-install command; using pdfjs-dist package in examples.
mozilla/pdf.js pull request #8401
Opened 2017-05-11 16:46 UTC by yurydelendik

It will simplify example usage (e.g. now examples can be copied and used as is in the custom project that has pdfjs-dist installed) and avoid git-tag error when `gulp dist` run.

2017-06-04 17:04 UTC, timvandermeij commented on README.md
> +More examples can be found at the examples folder. Some of them are using the pdfjs-dist package, which can be built and installed in this repo direcotry via `gulp dist-install` command.
Nit: `direcotry` should be `directory`

2017-06-04 17:05 UTC, timvandermeij commented
Could you update this patch to resolve the conflict?

2017-06-11 19:48 UTC, timvandermeij requested changes

2017-06-11 19:48 UTC, timvandermeij commented on examples/learning/helloworld.html
> +<script src="../../node_modules/pdfjs-dist/pdf.js"></script>
I think this should end with `/build/pdf.js` instead. Now it throws `ReferenceError: PDFJS is not defined`.

2017-06-12 15:22 UTC, yurydelendik commented on examples/learning/helloworld.html
> +<script src="../../node_modules/pdfjs-dist/pdf.js"></script>
Fixed, thanks.

2017-06-12 20:59 UTC, timvandermeij approved these changes

2017-06-12 20:59 UTC, merged

2017-06-12 20:59 UTC, timvandermeij commented
Thank you for fixing this!