Update pdf2svg.js
mozilla/pdf.js pull request #8461
Opened 2017-05-30 19:37 UTC by yshahin

Changing file write to sync solves the problem.
Looks like promise chaining with a file write at the end with out waiting for the write to happen causes the issue.

2017-05-30 19:43 UTC, yurydelendik commented
I wonder if there is a logical explanation to this fix -- node.js people recommend to use async callbacks.

> Looks like promise chaining with a file 

callback chaining

2017-05-30 22:12 UTC, timvandermeij requested changes

2017-05-30 22:12 UTC, timvandermeij commented on examples/node/pdf2svg.js
> +  if(!fs.existsSync('./svgdump/')) {
Add a space after `if`, so that it becomes `if (!fs....`.

2017-05-30 22:12 UTC, timvandermeij commented on examples/node/pdf2svg.js
> +    fs.mkdirSync('./svgdump/')
You need a semicolon at the end of the line.

2017-05-30 22:12 UTC, timvandermeij commented on examples/node/pdf2svg.js
> +  fs.writeFileSync('./svgdump/' + name + "-" + pageNum + '.svg', svgdump, 'utf-8');
Change the double quotes to single quotes on this line. Moreover, the prints are now gone. Is there a way to add them back?

2017-05-30 22:12 UTC, timvandermeij commented
I'm also wondering about the explanation for this. I'm fine with the sync approach if that works, but I do not understand why the async approach does not work properly.

2017-05-31 15:17 UTC, yshahin commented
I think the problem is not with the async calls but probably with when the call gets executed.
The "End Document" print statement gets printed before the write happens, which I think might be the cause.
By blocking the promise till the write happens this solves the problem.
There might be a way to do it with async calls but I did not figure it out yet.

Will continue working on it.

2017-05-31 16:22 UTC, yshahin commented
I tried different different things but only the sync file write works. I think we need to consult a node export here to tell us what the issue is. From the previous link it seems like a memory leak problem.

2017-05-31 16:25 UTC, yurydelendik commented
> By blocking the promise till the write happens this solves the problem.

I tried adding callback to block a promise -- the same problem.

> I tried different different things but only the sync file write works.

I'm worry it's just coincidence and the patch can be just masking the real problem, which can surface later.

2017-05-31 16:53 UTC, yurydelendik commented
Blocked by https://github.com/nodejs/node/issues/13337

2017-05-31 19:28 UTC, yurydelendik commented
node.js experts say it is a memory leak, so switching to sync might only fix the issue only for this case and can reappear in the future. I recommend to wait until leak will be found.

2017-05-31 23:00 UTC, yshahin commented
@yurydelendik take a look at this https://github.com/petkaantonov/bluebird/issues/1068 it seems like an inherit problem in promises in node.
The solution presented requires bluebird lib, I can try it out and see if it works.

2017-05-31 23:38 UTC, yurydelendik commented
@yshahin okay, pdf.js also have polyfill in compatibility.js, see if "forcing" it will help

2017-06-01 13:40 UTC, yurydelendik commented
@yashsriv the https://github.com/yurydelendik/nodesegfault/commit/2bb6f26c09309d942901c3d66fca3e6d3fdaf6f4 fixes the issue, so you are right it's due to Promises implementation.

2017-06-01 13:43 UTC, yurydelendik commented
Blocked by https://github.com/nodejs/help/issues/652

2017-06-01 20:57 UTC, yshahin commented
@yurydelendik how do you want to handle this?
Use the your fix? or change it to sync calls?

2017-06-01 21:27 UTC, timvandermeij commented
If it works with our promise polyfill and not with the native Node.js one, I'm not sure why the Node.js people claim the memory leak is on our side. Even if there is a memory leak, it shouldn't matter if you use sync/async writing.

Personally I'm fine with the sync approach here to solve this issue, but I'll let @yurydelendik make the call.

2017-06-18 11:35 UTC, Rob--W commented
I'm closing this PR in favor of mine at #8540, because moving from async to sync is unnecessary.

The reason that moving from async to sync "solves" the problem is that it forces Node.js to suspend execution until the file writing finishes. Consequently, pages are effectively processed sequentially.
My patch makes also changes the pdf2svg code to process the pages sequentially, but without blocking execution.

In this thread, it has been said that using our Promise polyfill solves the issue as well. I think that this is a mere coincidence. Normally promises are scheduled as a microtask, but with our [polyfill it is scheduled using setTimeout](https://github.com/mozilla/pdf.js/blob/8e9b4b5ff2be605895904db86be938d86a123016/src/shared/compatibility.js#L897-L967), which causes the promise to resolve less quickly. Consequently, when the SVG generation process (with many "promises") finishes, some file writing requests have likely finished as well, allowing Node.js to reclaim the memory for the string that is passed to `fs.writeFile` ([in pdf2svg.js](https://github.com/mozilla/pdf.js/blob/8e9b4b5ff2be605895904db86be938d86a123016/examples/node/pdf2svg.js#L21-L25)).

2017-06-18 11:35 UTC, closed without merging