Fix blank font loading issue.
mozilla/pdf.js pull request #8516
Opened 2017-06-12 14:23 UTC by githubBrandon

If a pdf (particularly in the form of an array buffer) has missing fonts, no fonts will display. This fixes that.

2017-06-12 14:29 UTC, yurydelendik requested changes
It's hard to understand the fix. The patch is missing the test and description does not provide an explanation for the fix. Things to be addressed: provide a comment why `=== 'function'` check is needed and add a test.

2017-06-12 14:29 UTC, yurydelendik commented on src/core/fonts.js
> +        if (typeof this._map[charCode].charCodeAt === 'function')
why not `typeof this._map[charCode] === 'string'` ?

2017-06-12 14:32 UTC, Snuffleupagus commented
> It's hard to understand the fix. The patch is missing the test and description does not provide an explanation for the fix. Things to be addressed: provide a comment why === 'function' check is needed and add a test.

Besides the above, won't this suffer from similar performance issues as issues/PRs #4183, #5411, #7064, #7394 (and probably more); which we have previously always rejected?

2017-06-12 14:35 UTC, githubBrandon commented on src/core/fonts.js
> +        if (typeof this._map[charCode].charCodeAt === 'function')
The error is `This._map[charCode].charCodeAt is not a function`. When seeing that error, no fonts are loaded. When this line is added, the pdf renders perfectly. I thought dealing with the error directly would be better, but I can test if `typeof this._map[charCode] === 'string'` works.

2017-06-12 14:37 UTC, githubBrandon commented
@Snuffleupagus I'm not sure in what way this relates to those. A simple type check should not have a noticeable impact on performance. This isn't changing prototypes for calling any helper functions.

2017-06-12 14:41 UTC, yurydelendik commented
> A simple type check should not have a noticeable impact on performance

Extra property check in the hot loops add a performance penalty. There is no reason to do that, unless there is a really good reason.

2017-06-12 14:44 UTC, Snuffleupagus commented
> I'm not sure in what way this relates to those. A simple type check should not have a noticeable impact on performance. This isn't changing prototypes for calling any helper functions.

In the issues/PRs I refereed to, the problem has been the use of JavaScript Libraries/Frameworks which adds custom properties/methods to Arrays in such a way that they become `enumerable` (which is *not* correct).
Hence these kind of added checks *should not* be necessary, and they will definitely have a non-zero performance cost!

I think the relevant question here is what the values of `charCode` and `this._map[charCode]` are when things break?

2017-06-12 14:46 UTC, yurydelendik commented on src/core/fonts.js
> +        if (typeof this._map[charCode].charCodeAt === 'function')
> When seeing that error, no fonts are loaded... I thought dealing with the error directly would be better

I'm thinking dealing with the error directly will slow down font parsing and will make PDF.js slower.

2017-06-22 21:55 UTC, timvandermeij commented
Closing since the pull request cannot be merged in the current state. No example PDF file has been provided that is fixed by this patch, the performance may be degraded by the patch and it's not clear why we even need such a check. If more information can be provided regarding these problems, we can consider reopening it.

2017-06-22 21:55 UTC, closed without merging