Allow for unbinding of events in web application
mozilla/pdf.js pull request #8525
Opened 2017-06-13 21:19 UTC by curiosity26

Allows for single page apps to unbind listeners when DOM element is destroyed in #8524

2017-06-13 21:39 UTC, yurydelendik commented on web/app.js
> +    eventBus.off('beforeprint', this.beforePrint.bind(this));
.bind() returns different function every time it is called, but eventBus.on and .off require the same method to be used.

2017-06-13 21:40 UTC, yurydelendik commented on web/app.js
> +    window.removeEventListener('resize', function windowResize() {
the methods windowResize is scoped only here and was not used for addEventListener.

2017-06-13 21:41 UTC, yurydelendik requested changes
The off() and removeEventListener() methods shall use the exact same methods that where used in on() and addEventListener().

2017-06-13 22:29 UTC, curiosity26 commented
Thanks Yury for the feedback. I'll make sure I cleanup those event listeners. I must be a little brain dead today because as I look at it now, it's glaringly obvious.

2017-06-14 08:39 UTC, Snuffleupagus commented on web/app.js
> +  unbindEvents: function pdfViewBindEvents() {
Since we support ES6 now, please use `unbindEvents() {` instead here (and similar in the method signature below as well).

2017-06-14 08:40 UTC, Snuffleupagus commented on web/app.js
> +    var eventBus = this.eventBus;
Please use `let` instead of `var` when adding new code (applies elsewhere in the patch as well).

2017-06-14 08:40 UTC, Snuffleupagus commented on web/app.js
> +        eventBus.off('fileinputchange', webViewerFileInputChange);
Please correct the indentation, since the standard in PDF.js is *two* spaces for indentation (applies in multiple places below as well).

2017-06-14 13:40 UTC, yurydelendik commented on web/app.js
> +    this._boundEvents.windowResize = (function () {
let's prefect ES6 syntax here, e.g.: 

```
this._boundEvents.windowResize = () => {
  this.dispatch('resize');
};
```

2017-06-14 13:42 UTC, yurydelendik commented on web/app.js
> +    this._boundEvents.windowChange = (function (evt) {
this code shall not be present in non-GENERIC build, can we keep this._boundEvents assignments interleaved with addEventListener

2017-06-14 13:43 UTC, yurydelendik commented on web/app.js
> +    delete this._boundEvents.windowResize;
Don't delete, just reset _boundEvents `this._boundEvents = {};` at the end.

2017-06-14 13:45 UTC, Snuffleupagus commented on web/app.js
> +   */
I'm not sure that we need such a verbose comment here (or a comment at all really).

2017-06-14 13:45 UTC, Snuffleupagus commented on web/app.js
> +    // Window Resize
These comments doesn't seem to add much value here!?

2017-06-14 13:47 UTC, Snuffleupagus commented on web/app.js
> +    }).bind(eventBus);
Please don't use `bind` needlessly; I think the following ought to work instead:
```javascript
this._boundEvents.windowResize = () => {
  eventListener.dispatch('resize');
};
```

2017-06-14 13:48 UTC, Snuffleupagus commented on web/app.js
> +        eventBus.off('fileinputchange', webViewerFileInputChange);
Here, and elsewhere, please remember to use *two* spaces when indenting.

2017-06-14 13:51 UTC, Snuffleupagus commented
Also, please remember to squash the commits when addressing review comments; see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits for information on this matter.

2017-06-14 13:53 UTC, curiosity26 commented on web/app.js
> +    }).bind(eventBus);
`eventListener` not `eventBus`?

2017-06-14 14:18 UTC, Snuffleupagus commented on web/app.js
> +    this._boundEvents.windowChange = (evt) => {
https://github.com/mozilla/pdf.js/pull/8525#discussion_r121949328 still appears to be unresolved in the latest version of the patch.

2017-06-14 14:19 UTC, Snuffleupagus commented on web/app.js
> +    delete this._boundEvents.windowResize;
https://github.com/mozilla/pdf.js/pull/8525#discussion_r121949651 still appears to be unresolved in the latest version of the patch.

2017-06-14 14:20 UTC, Snuffleupagus commented on web/app.js
> +        this._boundEvents.windowResize);
Nit: More indentation issues here, and below.
(And please don't forget to squash the commits.)

2017-06-15 21:15 UTC, timvandermeij commented
/botio-linux preview

2017-06-15 21:26 UTC, yurydelendik approved these changes

2017-06-17 20:32 UTC, timvandermeij approved these changes

2017-06-17 20:32 UTC, merged

2017-06-17 20:32 UTC, timvandermeij commented
Thank you for the patch!