Move svg:clipPath generation from clip to endPath
mozilla/pdf.js pull request #8542
Opened 2017-06-19 11:34 UTC by Rob--W

See the commit message for a detailed explanation.

I think that we also need to check whether it is necessary to add more `.endPath` calls to src/display/svg.js, similar to the many `consumePath` calls in src/display/canvas.js. However I don't understand that part of the code well enough to tell whether it's needed.

Fixes #8527

2017-06-19 11:37 UTC, Rob--W commented
/botio test

2017-06-21 21:47 UTC, timvandermeij requested changes

2017-06-21 21:47 UTC, timvandermeij commented on src/display/svg.js
> +    this.pendingClip = null;
It does not look like you store the pending clip in the `SVGExtraState` object (but instead as a property of `SVGGraphics`), so I think this should be moved to above https://github.com/mozilla/pdf.js/pull/8542/files?w=1#diff-84f753e2bb39669e059ce3447e5a0057R365, just like in `canvas.js`.

2017-06-21 21:47 UTC, timvandermeij commented on src/display/svg.js
> +      if (this.pendingClip) {
I think we should use this instead:

```javascript
if (!this.pendingClip) {
  return;
}
```

That way we avoid a level of indenting, which improves readability.

2017-06-21 23:13 UTC, Rob--W commented on src/display/svg.js
> +    this.pendingClip = null;
You're right, fixed.

2017-06-21 23:13 UTC, Rob--W commented on src/display/svg.js
> +      if (this.pendingClip) {
Done too.

2017-06-22 20:17 UTC, timvandermeij commented
/botio-linux preview

2017-06-22 20:20 UTC, timvandermeij commented
/botio test

2017-06-22 21:18 UTC, timvandermeij approved these changes

2017-06-22 21:18 UTC, timvandermeij commented
/botio makeref

2017-06-22 21:48 UTC, merged

2017-06-22 21:48 UTC, timvandermeij commented
Thank you for fixing this!