TypeError fix in colorspace.js
mozilla/pdf.js pull request #8666
Opened 2017-07-19 00:37 UTC by apoorv-mishra

Hi, 
**(Assumption: The base color space is set to be DeviceRGB)**
If an `Array`(not as `TypedArray` or `String`) is passed in `IndexedCS` constructor(https://github.com/mozilla/pdf.js/blob/master/src/core/colorspace.js#L509) as `lookup`, **TypeError** occurs on calling `fillRgb(...)`(on `IndexedCS` object), passing `lookup` as `comps`(https://github.com/mozilla/pdf.js/blob/master/src/core/colorspace.js#L116-L118). The error occurs because of `src.subarray(...)` in https://github.com/mozilla/pdf.js/blob/master/src/core/colorspace.js#L635 since `src` is expected to be a `TypedArray`. I made a small change to fix this.

2017-07-19 07:01 UTC, Snuffleupagus commented
/botio-linux preview

2017-07-19 07:27 UTC, Snuffleupagus commented
Thanks for the patch, but I've got a couple of questions/suggestions below.

Did you successfully run the reference tests locally, as explained in https://github.com/mozilla/pdf.js/wiki/Contributing, with this patch?
Looking at the IRC logs, in particular http://logs.glob.uno/?c=mozilla%23pdfjs&s=18+Jul+2017&e=18+Jul+2017#c64549, it mentions `TAMReview.pdf` as an example of Indexed ColorSpace usage. It appears that this patch unfortunately *breaks* at least that file, and thus quite possibly others as well.

From looking at the history of the code, see PR #3334, it appears that the *only* reason for supporting `Array` at all was for IE9 compatibility. Note that the `lookup` parameter, as coming from a PDF file, should *never* actually be a regular `Array`.
Wouldn't a better solution be to change [colorspace.js#L528-L529](https://github.com/mozilla/pdf.js/blob/4a74cc418ccb0b14dbbb50e0b964f32a41d16647/src/core/colorspace.js#L528-L529) to e.g. the following instead?
```javascript
} else if (lookup instanceof Uint8Array) {
  this.lookup = lookup;
} else if (lookup instanceof Array) {
  this.lookup = new Uint8Array(lookup);
```

Also, please update the commit message to something a little more descriptive, since it's really impossible to tell what the patch does based on just `TypeError fix in colorspace.js` without also reading the PR description. (In this case, even looking at the code itself doesn't really explain the reason for the change.)

2017-07-19 12:16 UTC, apoorv-mishra commented
Hi @Snuffleupagus , there is one more issue with making it as `Uint8Array`. Have a look at http://logs.glob.uno/?c=mozilla%23pdfjs&s=18+Jul+2017&e=18+Jul+2017#c64496.

2017-07-19 23:16 UTC, yurydelendik requested changes
Looks like you need to change getRgbItem -> getRgbBuffer call in the IndexedCS_getRgbItem above.

2017-07-20 19:17 UTC, yurydelendik commented on src/core/colorspace.js
> +      this.lookup = new Uint8Array(lookup);
Can you revert the changes above? For IE9, it will not matter.

2017-07-20 19:17 UTC, yurydelendik approved these changes
Looks good (with just getRgbBuffer change)

2017-07-20 19:18 UTC, apoorv-mishra commented on src/core/colorspace.js
> +      this.lookup = new Uint8Array(lookup);
Sure.

2017-07-20 19:41 UTC, yurydelendik commented
/botio test

2017-07-24 22:00 UTC, timvandermeij commented
/botio-linux preview

2017-07-24 22:05 UTC, timvandermeij commented
/botio test

2017-07-25 20:13 UTC, timvandermeij commented
Merging with r=yurydelendik. Thank you for the patch!

2017-07-25 20:13 UTC, merged