Confirm `eval` available before compiling PostScript. Fixes #5573
mozilla/pdf.js pull request #8815
Opened 2017-08-23 18:22 UTC by TheKidCoder

Compiling PS functions is only available if eval is available. Some sites might have `eval` disable via CSP. This includes the eval check.

2017-08-23 20:33 UTC, timvandermeij commented
Doesn't this break the functionality then? In other words, is there no way to avoid that by e.g., replacing `eval` in some way?

2017-08-23 20:34 UTC, timvandermeij requested changes

2017-08-23 20:34 UTC, timvandermeij commented on src/core/function.js
> +
Remove this whitespace.

2017-08-23 20:34 UTC, timvandermeij commented on src/core/function.js
> +      if (!!PDFJS.isEvalSupported) {
Travis CI has some complains about this line; could you check them?

2017-08-23 20:37 UTC, TheKidCoder commented
I don't fully understand what the benefit of the compiler is, but from some related comments I've come across it seems to only be there to improve speed. In the PDFs that were broken and now work, there is no visual difference. I'll fix the travis errors.

2017-08-23 20:40 UTC, timvandermeij commented
If that is indeed the case, then I'm fine with the change. It's a deliberate choice to disable `eval`, so users can expect less performance if they choose to do so.

@yurydelendik Could you chime in on if it's indeed only a performance loss and not a functionality loss?

2017-08-23 21:06 UTC, yurydelendik commented
It can be disabled and this will be a performance loss for some PDFs. There are some PDFs that use PS functions for colorspaces, that will make then slower -- based on #5134 4-5 times. But I think it's okay to disable the compilation when isEvalSupported = false -- not a problem for demo/generic viewer.

2017-08-23 21:08 UTC, timvandermeij commented
Thank you! In that case, this patch looks good with the comments addressed.

2017-08-23 21:13 UTC, yurydelendik commented on src/core/function.js
> +      if (!!PDFJS.isEvalSupported) {
PDFJS.isEvalSupported does not exist -- we removed all globals from PDFJS. This setting needs to be passed some other way.

2017-08-23 21:27 UTC, Snuffleupagus commented on src/core/function.js
> +      if (!!PDFJS.isEvalSupported) {
I'm assuming that we may also want to do something similar to https://github.com/mozilla/pdf.js/blob/23a4174163cba5709f05b04b371ee67b1d0148ca/src/display/font_loader.js#L401 and https://github.com/mozilla/pdf.js/blob/23a4174163cba5709f05b04b371ee67b1d0148ca/src/display/font_loader.js#L332 here as well?

2017-09-16 13:46 UTC, timvandermeij commented
Closing since this is superseded by #8909.

2017-09-16 13:46 UTC, closed without merging