Correctly validate the response status for non-HTTP fetch requests (PR 8768 follow-up)
mozilla/pdf.js pull request #8866
Opened 2017-09-02 10:09 UTC by Snuffleupagus

It seems that the status check, for non-HTTP loads, has been inverted which causes the default viewer to *refuse* to open local PDF files. *Follow-up to PR #8768.

***STR:***
 1. Make sure that fetch support is enabled in the browser. In Firefox Nightly, set `dom.streams.enabled = true` and `javascript.options.streams = true` in `about:config`.
 2. Open https://mozilla.github.io/pdf.js/web/viewer.html.
 3. Click on the "Open file" button, and open a new PDF file.

***ER:***
 A new PDF file should open in the viewer.

***AR:***
 The PDF file fails to open, with an error message of the following format:
`Message: Unexpected server response (200) while retrieving PDF "blob:https://mozilla.github.io/a4fc455f-bc05-45b5-b6aa-2ecff3cb45ce".`

2017-09-02 10:10 UTC, Snuffleupagus commented
/botio-linux preview

2017-09-05 11:04 UTC, Snuffleupagus commented
/botio test

2017-09-05 14:49 UTC, yurydelendik requested changes
Let's remove entire if(!isHttp) statement. Not sure if fetch() for file: protocol is returning 0 for success.

2017-09-05 15:06 UTC, Snuffleupagus commented
> Let's remove entire if(!isHttp) statement.

Fixed now, thanks!

> Not sure if fetch() for file: protocol is returning 0 for success.

According to https://fetch.spec.whatwg.org/#scheme-fetch, it would seem that `file://` isn't even in the specification.

2017-09-05 15:10 UTC, Snuffleupagus commented
/botio-linux preview

2017-09-05 15:19 UTC, yurydelendik approved these changes

2017-09-05 17:22 UTC, yurydelendik commented
/botio-linux test

2017-09-05 17:47 UTC, merged

2017-09-05 17:47 UTC, yurydelendik commented
Thank you for the patch.

2017-09-05 17:53 UTC, mukulmishra18 commented
> According to https://fetch.spec.whatwg.org/#scheme-fetch, it would seem that file:// support isn't even properly defined in the specification.

`file:` protocol is not supported by the native fetch implementation and always throws `TypeError`, see https://github.com/github/fetch/issues/186 .