Add CDN links
mozilla/pdf.js pull request #8980
Opened 2017-09-30 21:05 UTC by LukasDrgon

I added [jsDelivr CDN links](https://www.jsdelivr.com/package/npm/pdfjs-dist) to your site and readme for easier and faster usage. jsDelivr is the fastest opensource CDN available and built specifically for production usage.

2017-09-30 21:14 UTC, Snuffleupagus commented
I'm not sure that we, first of all, should advertise a *specific* CDN in this very visible way!?
Secondly, even if we do this, I don't really think that it belongs in https://mozilla.github.io/pdf.js/getting_started, since it should contain just the bare minimum.
Finally, if added to `README.md`, it shouldn't be placed in such a way that it takes precedence over the existing "Getting the Code" section (since that is the only thing we can really guarantee work).

2017-09-30 22:05 UTC, LukasDrgon commented
>I'm not sure that we, first of all, should (effectively) endorse a specific CDN in this very visible way!?

That is, of course, completely up to you. Most JS projects do provide a CDN link in their README/documentation because it makes using the code easier (and using a CDN is usually better than serving files from your server).

From user's POV, I can say that the getting started page is exactly where I would expect this, in addition to the full zip packages, but I'll be happy to modify this PR if you decide you actually want this *somewhere*.

2017-09-30 22:12 UTC, jimaek commented
Interestingly enough Mozilla has covered jsDelivr before :) https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

2017-10-01 02:44 UTC, yurydelendik commented
What jsDeliver provides that cd.js or npmcdn does not? Does jsDeliver allow cors to access cmaps?

2017-10-01 07:04 UTC, MartinKolarik commented
@yurydelendik 
 - Multiple CDN providers, including one in China, which results in better load times.
 - Also multiple DNS providers, origin server locations, and backup storage system - it's visually explained [here](https://www.jsdelivr.com/network/infographic) and means that even if half of the services we use went down at the same time, jsDelivr would still continue to work.
 - Support for on-demand minification and bundling of multiple JS/CSS files. 
 - Usage statistics per project/version/file (some developers actually use this to drive certain development decisions).
 - Similarly to npmcdn, instant updates from npm with zero config, and semver version ranges for auto-updating URLs, such as `/npm/pdfjs-dist@1`

>Does jsDeliver allow cors to access cmaps?

Yes, cors is enabled for all resources.

2017-10-01 18:35 UTC, yurydelendik commented
> > Does jsDeliver allow cors to access cmaps?

> Yes, cors is enabled for all resources.

I test the https://gist.github.com/yurydelendik/016016dcb126ee5c84b4a9c3cc734d8e example. The CORS at jsDeliver does not work. I tested npmcdn.com it works there.

2017-10-01 18:42 UTC, yurydelendik requested changes
We want to provide an alternative CDNs and don't want to be exclusive to the jsDelivr. Please rephrase text in neutral language and list available/popular CDNs that host PDF.js at this moment.

2017-10-01 18:42 UTC, yurydelendik commented on README.md
> +<script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@1/build/pdf.min.js"></script>
We cannot exclusively list only jsdelivr, please list npmcdn.com prior jsdelivr.net since some finality (e.g. cmaps) does not work with the former.

2017-10-01 18:42 UTC, yurydelendik commented on docs/contents/getting_started/index.md
> +You can use PDF.js by including this file from [jsDelivr](https://www.jsdelivr.com/package/npm/pdfjs-dist):
Remove the text from the download section, list it in the separate section below.

2017-10-01 18:46 UTC, MartinKolarik commented
I think you just used a wrong link there. https://www.jsdelivr.com/ is the website, CDN files are on a different domain - https://cdn.jsdelivr.net/npm/pdfjs-dist/cmaps/

2017-10-01 18:48 UTC, yurydelendik commented
> I think you just used a wrong link there. https://www.jsdelivr.com/ is the website, 

Sorry, I just copied what is/was provided at https://github.com/mozilla/pdf.js/pull/8980/commits/a8d73975d976d0d96bc1a2486489fbfbb9c108f7#diff-04c6e90faac2675aa89e2176d2eec7d8R50

2017-10-02 19:13 UTC, LukasDrgon commented
@yurydelendik Let me know if you want to change anything else.

2017-10-02 19:50 UTC, yurydelendik approved these changes

2017-10-02 19:51 UTC, yurydelendik commented on README.md
> +## Including via a CDN
Can you move this section after `## Using PDF.js in a web application`?

2017-10-02 19:52 UTC, timvandermeij commented
@LukasDrgon Also, please squash the commits into one commit (see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits) once you made the change requested above.

2017-10-02 21:02 UTC, LukasDrgon commented
All done 👍

2017-10-03 20:50 UTC, timvandermeij approved these changes

2017-10-03 20:51 UTC, merged

2017-10-03 20:51 UTC, timvandermeij commented
Thank you for the patch!