Improve node.js support
mozilla/pdf.js pull request #9588
Opened 2018-03-20 09:16 UTC by swftvsn

This change fixes "Unhandled rejection ReferenceError: HTMLElement is not defined" issue that is discussed in more detail in #8489.

2018-03-20 23:41 UTC, brendandahl requested changes
You have some lint failures.

2018-03-21 04:54 UTC, swftvsn commented
Second commit should fix that. On a side note, we all have wide screens even on laptops, so imho capping the line length to 80 chars only makes the code harder to read in most cases. But that's just a matter of personal preference of course, I use 200 on my projects and still have ample space on any display.

2018-03-21 08:52 UTC, Snuffleupagus commented on src/display/canvas.js
> +           !imgData.data) {
This line is indented with one space too many; let's re-format it like this instead:
```javascript
if ((typeof HTMLElement === 'function' &&
     imgData instanceof HTMLElement) || !imgData.data) {
```

Also, please squash the commits; refer to https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

2018-03-21 11:46 UTC, swftvsn commented
@Snuffleupagus The if is now formatted per spec you gave, and the commits are squashed. Thanks for the excellent squash tutorial! (https://github.com/mozilla/pdf.js/wiki/Squashing-Commits)

2018-03-26 20:20 UTC, timvandermeij commented
/botio test

2018-04-01 10:21 UTC, timvandermeij commented
/botio-linux preview

2018-04-01 10:26 UTC, timvandermeij approved these changes

2018-04-01 10:26 UTC, merged

2018-04-01 10:26 UTC, timvandermeij commented
Thank you for fixing this!