Proper Error Handling for Build Numbers of Downloaded Sources (Non-Git repositories).
mozilla/pdf.js pull request #9852
Opened 2018-06-28 19:35 UTC by RonLek

Implemented proper Error Handling along with error message for pdf.js downloaded from other sources like the PDF.JS Mozilla Release Page.
https://github.com/mozilla/pdf.js/releases

Closes #9834

2018-06-28 21:27 UTC, timvandermeij requested changes

2018-06-29 06:44 UTC, RonLek commented
Thanks for the review @timvandermeij . I've made the requested changes. Please review.

2018-06-29 06:52 UTC, RonLek commented
Thanks for reviewing @timvandermeij . I've made the changes.

2018-06-29 07:46 UTC, Snuffleupagus commented
> I've made the changes.

The patch now contains mostly unrelated/unwanted changes; why did you change the indentation of the entire file? All indentation changes need to be reverted, such that the entire diff contains *nothing* more than the following changes (based on the review comments above):
```diff
diff --git a/gulpfile.js b/gulpfile.js
index c7e66a20..919201ee 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -449,6 +449,8 @@ gulp.task('buildnumber', function (done) {
     if (!err) {
       // Build number is the number of commits since base version
       buildNumber = stdout ? stdout.match(/\n/g).length : 0;
+    } else {
+      console.log('This is not a Git repository; using default build number.');
     }

     console.log('Extension build number: ' + buildNumber);
```

Finally, please see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

2018-06-29 08:16 UTC, Snuffleupagus commented on gulpfile.js
> +      console.log('Using default build number.');
This should fit on *one* line, i.e. format it as `console.log('This is not a Git repository; using default build number.');` which is what https://github.com/mozilla/pdf.js/pull/9852#discussion_r198991482 asked for.

You also need to squash the commits, see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

2018-06-29 13:35 UTC, RonLek commented
Will be making a new pull request.

2018-06-29 13:40 UTC, RonLek commented
@Snuffleupagus I'm new to contributing to GitHub. 
When I downloaded my forked PDFjs repository from GitHub and performed git log it gives me "Your current branch has no commits yet" even though I have 5 commits in my GitHub forked repository.
Can you help me?

2018-06-29 16:42 UTC, RonLek commented
@Snuffleupagus @timvandermeij After spending a lot of time on GitHub Help pages I finally I figured out what I had to do! Can you guys please review. Sorry for the trouble.

2018-06-29 21:11 UTC, timvandermeij approved these changes

2018-06-29 21:12 UTC, merged

2018-06-29 21:12 UTC, timvandermeij commented
Looks good now. Thank you for your contribution!