Modified Examples to work without systemjs
mozilla/pdf.js pull request #9904
Opened 2018-07-20 20:57 UTC by RonLek

Closes #9784 

@timvandermeij  @Snuffleupagus  Please review for changes, if any. Thanks!

2018-07-21 09:28 UTC, Snuffleupagus requested changes

2018-07-21 10:56 UTC, RonLek commented
@Snuffleupagus Thanks for reviewing. Made the changes!

2018-07-21 11:06 UTC, timvandermeij commented on README.md
> ++ [examples/learning/helloworld](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html)
Yes, I fully agree with this.

2018-07-21 11:18 UTC, Snuffleupagus commented on README.md
>  More examples can be found in the examples folder. Some of them are using the pdfjs-dist package, which can be built and installed in this repo directory via `gulp dist-install` command.
Nit: Maybe it wouldn't be a bad idea to also make "examples folder" text into a link, i.e. change it to
```
[examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/)
```

2018-07-21 11:19 UTC, Snuffleupagus commented on README.md
>  More examples can be found in the examples folder. Some of them are using the pdfjs-dist package, which can be built and installed in this repo directory via `gulp dist-install` command.
Nit: Maybe it wouldn't be a bad idea to change the "examples folder" text into a link, i.e. like so:
[examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/)
```

2018-07-21 11:20 UTC, Snuffleupagus commented on README.md
>  More examples can be found in the examples folder. Some of them are using the pdfjs-dist package, which can be built and installed in this repo directory via `gulp dist-install` command.
Nit: Maybe it wouldn't be a bad idea to change the "examples folder" text into a link, i.e. like so:
```
[examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/)
```

2018-07-21 11:31 UTC, RonLek commented
And Done!!

2018-07-21 11:33 UTC, Snuffleupagus approved these changes

2018-07-22 12:55 UTC, timvandermeij approved these changes

2018-07-22 12:55 UTC, merged

2018-07-22 12:55 UTC, timvandermeij commented
Nice work; thank you for your contribution!