Use the Font Loading API in `MOZCENTRAL` builds, and `GENERIC` builds for Firefox version 63 and above (issue 9945)
mozilla/pdf.js pull request #9982
Opened 2018-08-17 09:13 UTC by Snuffleupagus

*I was feeling bored, so this is an attempt at fixing issue #9945.*

2018-08-17 09:16 UTC, Snuffleupagus commented
/botio test

2018-08-17 22:42 UTC, Snuffleupagus commented
/botio-linux preview

2018-08-22 21:20 UTC, brendandahl requested changes

2018-08-24 13:50 UTC, Snuffleupagus commented
/botio test

2018-08-29 13:38 UTC, Snuffleupagus commented
/botio-windows preview

2018-09-08 17:10 UTC, Snuffleupagus commented
/botio test

2018-09-18 17:46 UTC, mark-i-m commented
Any progress on this? It would be nice to have the printing issues fixed. Thanks!

2018-09-19 19:28 UTC, brendandahl commented
I want to hold off on this until the end of the week so #9340 has more time to bake in Firefox Nightly. It was a pretty large change and it will be easier to see if any regression come from it or this change if they are spread out a bit.

2018-09-29 14:50 UTC, Snuffleupagus commented
/botio test

2018-10-01 18:09 UTC, brendandahl commented
/botio-windows test

2018-10-01 18:38 UTC, brendandahl commented
/botio-windows test

2018-10-01 20:44 UTC, merged